import { r100AdvisoryHumanReviewCoordinationCategories } from "@/lib/r100-controlled-human-review-coordination-scope-contract";
import { r100BlockedDriftTransitions } from "@/lib/r100-controlled-human-review-coordination-drift-risk-audit";
import { r100ReadonlyUiWording } from "@/lib/r100-controlled-human-review-coordination-readonly-ui-scope-contract";

type ReviewCoordinationSignal = { title: string; status: string; detail: string };
const safetyBadges = ["Read-only", "Advisory only", "Manual review", "No provider"];
const reviewCoordinationSignals: ReviewCoordinationSignal[] = [
  { title: "Manual human review coordination review", status: r100ReadonlyUiWording.manualHumanReviewCoordinationReview, detail: "Human review coordination review labels help humans inspect blocked, incomplete, low-confidence, and high-priority risk areas without changing records." },
  { title: "Operator coordination", status: r100ReadonlyUiWording.operatorCoordination, detail: "Coordination visibility is advisory only and cannot activate providers, outreach, automation, or contact." },
  { title: "Command-level risk handling", status: r100ReadonlyUiWording.operatorReviewedHumanReviewCoordination, detail: "Command-level human review coordination summaries support manual review while runtime jobs, polling, and automation remain blocked." },
  { title: "High-impact review coordination", status: r100ReadonlyUiWording.highImpactReviewCoordination, detail: "High-impact review coordination does not authorize provider activation, scraping, skip tracing, or lead creation." },
  { title: "Escalation review coordination", status: r100ReadonlyUiWording.escalationReviewCoordination, detail: "Escalation review coordination remains a human review signal and cannot trigger contact." },
  { title: "Governance boundary", status: r100ReadonlyUiWording.governanceHumanReviewCoordinationReview, detail: `${r100ReadonlyUiWording.noExecution} ${r100ReadonlyUiWording.coordinationDoesNotGrantExecution} ${r100ReadonlyUiWording.noProvider} ${r100ReadonlyUiWording.noContact}` },
];
function formatCategory(value: string) { return value.replaceAll("-", " "); }
export function ControlledHumanReviewCoordinationSummary() {
  return (
    <section aria-labelledby="controlled-human-review-coordination-heading" aria-describedby="controlled-human-review-coordination-summary" className="overflow-hidden rounded-[1.5rem] border border-border bg-surface p-5 sm:p-6">
      <div className="flex min-w-0 flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div className="min-w-0 space-y-2"><p className="break-words text-sm font-semibold uppercase tracking-[0.16em] text-muted">Controlled human review coordination</p><h2 id="controlled-human-review-coordination-heading" className="break-words text-xl font-semibold text-primary">Read-only controlled human review coordination intelligence</h2><p id="controlled-human-review-coordination-summary" className="max-w-3xl break-words text-sm leading-6 text-muted">{r100ReadonlyUiWording.humanReviewCoordination} It helps operators review manual human review preparation needs, operator coordination, command-level review coordination summaries, high-impact review coordination, blocked paths, incomplete and low-confidence human review coordination review signals, revenue continuity human review coordination risk, risk-path review coordination review, escalation review coordination, governance review coordination, and manual-only review coordination insight. Human review coordination does not authorize execution or route work. No execution, provider activation, outreach, automation, lead generation, scraping, skip tracing, MLS/public-record behavior, fetch/network behavior, runtime job, polling, persistence, audit writing, or contact is authorized.</p></div>
        <div className="flex max-w-full flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.1em]">{safetyBadges.map((badge) => <span key={badge} className="max-w-full break-words rounded-full border border-border bg-white px-3 py-1 text-center leading-5 text-primary">{badge}</span>)}</div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{reviewCoordinationSignals.map((item) => <article key={item.title} className="min-w-0 rounded-2xl border border-border bg-white p-4"><h3 className="break-words text-sm font-semibold text-primary">{item.title}</h3><p className="mt-2 break-words text-sm font-medium text-primary">{item.status}</p><p className="mt-1 break-words text-sm leading-6 text-muted">{item.detail}</p></article>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Advisory human review coordination categories</h3><div className="mt-3 flex max-w-full flex-wrap gap-2">{r100AdvisoryHumanReviewCoordinationCategories.map((category) => <span key={category} className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 text-xs font-bold leading-5 text-blue-950">{formatCategory(category)}</span>)}</div></div><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Human review coordination drift boundary</h3><ul className="mt-2 list-disc space-y-1 pl-5">{r100BlockedDriftTransitions.slice(0, 7).map((transition) => <li key={transition} className="break-words">{transition}</li>)}</ul></div></div>
      <div className="mt-4 flex max-w-full flex-wrap gap-2 text-xs font-bold"><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">readOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">advisoryOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">simulationOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerCalled:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">sent:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">persistenceAllowedNow:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">pollingAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">runtimeActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">approvalGrantsExecution:false</span></div>
    </section>
  );
}
