import { r93AdvisoryRiskCommandCategories } from "@/lib/r93-revenue-risk-review-command-scope-contract";
import { r93BlockedDriftTransitions } from "@/lib/r93-revenue-risk-review-command-drift-risk-audit";
import { r93ReadonlyUiWording } from "@/lib/r93-revenue-risk-review-command-readonly-ui-scope-contract";

type RiskCommandSignal = { title: string; status: string; detail: string };
const safetyBadges = ["Read-only", "Advisory only", "Manual review", "No provider"];
const riskCommandSignals: RiskCommandSignal[] = [
  { title: "Manual risk command review", status: r93ReadonlyUiWording.manualRiskReview, detail: "Risk command labels help humans inspect warning summaries, incomplete signals, and low-confidence risk review areas without changing records." },
  { title: "Operator risk coordination", status: r93ReadonlyUiWording.operatorRiskCoordination, detail: "Coordination visibility is advisory only and cannot activate providers, outreach, automation, or contact." },
  { title: "Early-warning review", status: r93ReadonlyUiWording.earlyWarningReview, detail: "Early-warning review may support human inspection while runtime jobs, polling, and automation remain blocked." },
  { title: "Revenue continuity risk", status: r93ReadonlyUiWording.revenueContinuityRisk, detail: "Continuity risk review does not authorize outreach, contact, provider activation, scraping, or skip tracing." },
  { title: "Pipeline fragility review", status: r93ReadonlyUiWording.pipelineFragilityReview, detail: "Pipeline fragility review stays manual and cannot activate provider behavior." },
  { title: "Governance boundary", status: r93ReadonlyUiWording.governance, detail: `${r93ReadonlyUiWording.noExecution} ${r93ReadonlyUiWording.noProvider} ${r93ReadonlyUiWording.noContact}` },
];
function formatCategory(value: string) { return value.replaceAll("-", " "); }
export function RevenueRiskReviewCommandSummary() {
  return (
    <section aria-labelledby="revenue-risk-review-command-heading" aria-describedby="revenue-risk-review-command-summary" className="overflow-hidden rounded-[1.5rem] border border-border bg-surface p-5 sm:p-6">
      <div className="flex min-w-0 flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div className="min-w-0 space-y-2"><p className="break-words text-sm font-semibold uppercase tracking-[0.16em] text-muted">Revenue risk review command</p><h2 id="revenue-risk-review-command-heading" className="break-words text-xl font-semibold text-primary">Read-only revenue risk review intelligence</h2><p id="revenue-risk-review-command-summary" className="max-w-3xl break-words text-sm leading-6 text-muted">{r93ReadonlyUiWording.riskReviewCommand} It helps operators review risk command needs, manual risk review requirements, operator risk coordination, early-warning review, revenue continuity risk, pipeline fragility review, escalation review, governance review, incomplete risk review signals, low-confidence risk review, blocked paths, high-impact risk review, and command-level risk summaries. No execution, provider activation, outreach, automation, lead generation, scraping, skip tracing, MLS/public-record behavior, fetch/network behavior, runtime job, polling, persistence, audit writing, or contact is authorized.</p></div>
        <div className="flex max-w-full flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.1em]">{safetyBadges.map((badge) => <span key={badge} className="max-w-full break-words rounded-full border border-border bg-white px-3 py-1 text-center leading-5 text-primary">{badge}</span>)}</div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{riskCommandSignals.map((item) => <article key={item.title} className="min-w-0 rounded-2xl border border-border bg-white p-4"><h3 className="break-words text-sm font-semibold text-primary">{item.title}</h3><p className="mt-2 break-words text-sm font-medium text-primary">{item.status}</p><p className="mt-1 break-words text-sm leading-6 text-muted">{item.detail}</p></article>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Advisory risk command categories</h3><div className="mt-3 flex max-w-full flex-wrap gap-2">{r93AdvisoryRiskCommandCategories.map((category) => <span key={category} className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 text-xs font-bold leading-5 text-blue-950">{formatCategory(category)}</span>)}</div></div><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Risk command drift boundary</h3><ul className="mt-2 list-disc space-y-1 pl-5">{r93BlockedDriftTransitions.slice(0, 7).map((transition) => <li key={transition} className="break-words">{transition}</li>)}</ul></div></div>
      <div className="mt-4 flex max-w-full flex-wrap gap-2 text-xs font-bold"><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">readOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">advisoryOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">simulationOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerCalled:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">sent:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">persistenceAllowedNow:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">pollingAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">runtimeActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">approvalGrantsExecution:false</span></div>
    </section>
  );
}
