import { r92AdvisoryWarningCategories } from "@/lib/r92-revenue-risk-early-warning-scope-contract";
import { r92BlockedDriftTransitions } from "@/lib/r92-revenue-risk-early-warning-drift-risk-audit";
import { r92ReadonlyUiWording } from "@/lib/r92-revenue-risk-early-warning-readonly-ui-scope-contract";

type RiskSignal = { title: string; status: string; detail: string };
const safetyBadges = ["Read-only", "Advisory only", "Manual review", "No provider"];
const riskSignals: RiskSignal[] = [
  { title: "Manual risk review", status: r92ReadonlyUiWording.manualRiskReview, detail: "Early-warning labels help humans inspect revenue risk, incomplete signals, and low-confidence warning areas without changing records." },
  { title: "Pipeline fragility", status: r92ReadonlyUiWording.pipelineFragility, detail: "Fragility visibility is advisory only and cannot activate provider behavior." },
  { title: "Revenue continuity threat", status: r92ReadonlyUiWording.revenueContinuityThreat, detail: "Continuity threat signals may support human review while runtime jobs, polling, and automation remain blocked." },
  { title: "Delayed workflow risk", status: r92ReadonlyUiWording.delayedWorkflowRisk, detail: "Delayed workflow risk does not authorize outreach, contact, provider activation, scraping, or skip tracing." },
  { title: "Operator risk coordination", status: r92ReadonlyUiWording.revenueRisk, detail: "Operator review is required before any real-world action." },
  { title: "Governance boundary", status: r92ReadonlyUiWording.governance, detail: `${r92ReadonlyUiWording.noExecution} ${r92ReadonlyUiWording.noProvider} ${r92ReadonlyUiWording.noContact}` },
];
function formatCategory(value: string) { return value.replaceAll("-", " "); }
export function RevenueRiskEarlyWarningSummary() {
  return (
    <section aria-labelledby="revenue-risk-early-warning-heading" aria-describedby="revenue-risk-early-warning-summary" className="overflow-hidden rounded-[1.5rem] border border-border bg-surface p-5 sm:p-6">
      <div className="flex min-w-0 flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div className="min-w-0 space-y-2"><p className="break-words text-sm font-semibold uppercase tracking-[0.16em] text-muted">Revenue risk early warning</p><h2 id="revenue-risk-early-warning-heading" className="break-words text-xl font-semibold text-primary">Read-only revenue risk intelligence</h2><p id="revenue-risk-early-warning-summary" className="max-w-3xl break-words text-sm leading-6 text-muted">{r92ReadonlyUiWording.earlyWarning} It helps operators review early risk, revenue warning signals, pipeline fragility, revenue continuity threats, delayed workflow risk, incomplete risk signals, low-confidence risk signals, escalation review, governance review, high-impact risk, blocked risk paths, risk-awareness-only labels, and operator risk coordination needs. No execution, provider activation, outreach, automation, lead generation, scraping, skip tracing, MLS/public-record behavior, fetch/network behavior, runtime job, polling, persistence, audit writing, or contact is authorized.</p></div>
        <div className="flex max-w-full flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.1em]">{safetyBadges.map((badge) => <span key={badge} className="max-w-full break-words rounded-full border border-border bg-white px-3 py-1 text-center leading-5 text-primary">{badge}</span>)}</div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{riskSignals.map((item) => <article key={item.title} className="min-w-0 rounded-2xl border border-border bg-white p-4"><h3 className="break-words text-sm font-semibold text-primary">{item.title}</h3><p className="mt-2 break-words text-sm font-medium text-primary">{item.status}</p><p className="mt-1 break-words text-sm leading-6 text-muted">{item.detail}</p></article>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Advisory risk categories</h3><div className="mt-3 flex max-w-full flex-wrap gap-2">{r92AdvisoryWarningCategories.map((category) => <span key={category} className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 text-xs font-bold leading-5 text-blue-950">{formatCategory(category)}</span>)}</div></div><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Early-warning drift boundary</h3><ul className="mt-2 list-disc space-y-1 pl-5">{r92BlockedDriftTransitions.slice(0, 7).map((transition) => <li key={transition} className="break-words">{transition}</li>)}</ul></div></div>
      <div className="mt-4 flex max-w-full flex-wrap gap-2 text-xs font-bold"><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">readOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">advisoryOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">simulationOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerCalled:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">sent:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">persistenceAllowedNow:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">pollingAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">runtimeActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">approvalGrantsExecution:false</span></div>
    </section>
  );
}
