import { r91AdvisoryStabilityCategories } from "@/lib/r91-revenue-resilience-stabilization-scope-contract";
import { r91BlockedDriftTransitions } from "@/lib/r91-revenue-resilience-stabilization-drift-risk-audit";
import { r91ReadonlyUiWording } from "@/lib/r91-revenue-resilience-stabilization-readonly-ui-scope-contract";

type StabilitySignal = { title: string; status: string; detail: string };
const safetyBadges = ["Read-only", "Advisory only", "Manual review", "No provider"];
const stabilitySignals: StabilitySignal[] = [
  { title: "Manual resilience review", status: r91ReadonlyUiWording.manualReview, detail: "Resilience labels help humans inspect fragile revenue paths, continuity risk, and low-confidence stability signals without changing records." },
  { title: "Stabilization readiness", status: r91ReadonlyUiWording.stabilization, detail: "Stabilization readiness is advisory only and cannot become automated workflow stabilization." },
  { title: "Revenue continuity risk", status: r91ReadonlyUiWording.revenueContinuity, detail: "Continuity signals may support human review while runtime jobs, polling, and automation remain blocked." },
  { title: "Pipeline health review", status: r91ReadonlyUiWording.pipelineHealth, detail: "Pipeline health visibility does not authorize outreach or contact." },
  { title: "Manual resilience planning", status: r91ReadonlyUiWording.manualResiliencePlanning, detail: "Operator review is required before any real-world action." },
  { title: "Governance boundary", status: r91ReadonlyUiWording.governance, detail: `${r91ReadonlyUiWording.noExecution} ${r91ReadonlyUiWording.noProvider} ${r91ReadonlyUiWording.noContact}` },
];
function formatCategory(value: string) { return value.replaceAll("-", " "); }
export function RevenueResilienceStabilizationSummary() {
  return (
    <section aria-labelledby="revenue-resilience-stabilization-heading" aria-describedby="revenue-resilience-stabilization-summary" className="overflow-hidden rounded-[1.5rem] border border-border bg-surface p-5 sm:p-6">
      <div className="flex min-w-0 flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div className="min-w-0 space-y-2"><p className="break-words text-sm font-semibold uppercase tracking-[0.16em] text-muted">Manual revenue resilience stabilization</p><h2 id="revenue-resilience-stabilization-heading" className="break-words text-xl font-semibold text-primary">Read-only revenue resilience intelligence</h2><p id="revenue-resilience-stabilization-summary" className="max-w-3xl break-words text-sm leading-6 text-muted">{r91ReadonlyUiWording.revenueResilience} It helps operators review stabilization readiness, revenue continuity risk, fragile revenue paths, pipeline health, operational continuity, manual resilience planning, low-confidence stability signals, escalation review, and governance review needs. No execution, provider activation, outreach, automation, lead generation, scraping, skip tracing, MLS/public-record behavior, fetch/network behavior, runtime job, polling, persistence, audit writing, or contact is authorized.</p></div>
        <div className="flex max-w-full flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.1em]">{safetyBadges.map((badge) => <span key={badge} className="max-w-full break-words rounded-full border border-border bg-white px-3 py-1 text-center leading-5 text-primary">{badge}</span>)}</div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{stabilitySignals.map((item) => <article key={item.title} className="min-w-0 rounded-2xl border border-border bg-white p-4"><h3 className="break-words text-sm font-semibold text-primary">{item.title}</h3><p className="mt-2 break-words text-sm font-medium text-primary">{item.status}</p><p className="mt-1 break-words text-sm leading-6 text-muted">{item.detail}</p></article>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Advisory resilience categories</h3><div className="mt-3 flex max-w-full flex-wrap gap-2">{r91AdvisoryStabilityCategories.map((category) => <span key={category} className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 text-xs font-bold leading-5 text-blue-950">{formatCategory(category)}</span>)}</div></div><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Stabilization drift boundary</h3><ul className="mt-2 list-disc space-y-1 pl-5">{r91BlockedDriftTransitions.slice(0, 7).map((transition) => <li key={transition} className="break-words">{transition}</li>)}</ul></div></div>
      <div className="mt-4 flex max-w-full flex-wrap gap-2 text-xs font-bold"><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">readOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">advisoryOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">simulationOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerCalled:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">sent:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">persistenceAllowedNow:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">pollingAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">runtimeActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">approvalGrantsExecution:false</span></div>
    </section>
  );
}
