import { r98AdvisoryCommandCategories } from "@/lib/r98-revenue-risk-recommendation-review-command-scope-contract";
import { r98BlockedDriftTransitions } from "@/lib/r98-revenue-risk-recommendation-review-command-drift-risk-audit";
import { r98ReadonlyUiWording } from "@/lib/r98-revenue-risk-recommendation-review-command-readonly-ui-scope-contract";

type CommandSignal = { title: string; status: string; detail: string };
const safetyBadges = ["Read-only", "Advisory only", "Manual review", "No provider"];
const commandSignals: CommandSignal[] = [
  { title: "Manual command review", status: r98ReadonlyUiWording.manualCommandReview, detail: "Command review labels help humans inspect blocked, incomplete, low-confidence, and high-priority risk areas without changing records." },
  { title: "Operator coordination", status: r98ReadonlyUiWording.operatorCoordination, detail: "Coordination visibility is advisory only and cannot activate providers, outreach, automation, or contact." },
  { title: "Command-level risk handling", status: r98ReadonlyUiWording.operatorReviewedCommand, detail: "Command-level review summaries support manual review while runtime jobs, polling, and automation remain blocked." },
  { title: "High-impact command", status: r98ReadonlyUiWording.highImpactCommand, detail: "High-impact command does not authorize provider activation, scraping, skip tracing, or lead creation." },
  { title: "Escalation command", status: r98ReadonlyUiWording.escalationCommand, detail: "Escalation command remains a human review signal and cannot trigger contact." },
  { title: "Governance boundary", status: r98ReadonlyUiWording.governanceCommandReview, detail: `${r98ReadonlyUiWording.noExecution} ${r98ReadonlyUiWording.noProvider} ${r98ReadonlyUiWording.noContact}` },
];
function formatCategory(value: string) { return value.replaceAll("-", " "); }
export function RevenueRiskRecommendationReviewCommandSummary() {
  return (
    <section aria-labelledby="revenue-risk-recommendation-review-command-heading" aria-describedby="revenue-risk-recommendation-review-command-summary" className="overflow-hidden rounded-[1.5rem] border border-border bg-surface p-5 sm:p-6">
      <div className="flex min-w-0 flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div className="min-w-0 space-y-2"><p className="break-words text-sm font-semibold uppercase tracking-[0.16em] text-muted">Revenue risk recommendation review command</p><h2 id="revenue-risk-recommendation-review-command-heading" className="break-words text-xl font-semibold text-primary">Read-only revenue risk recommendation review command intelligence</h2><p id="revenue-risk-recommendation-review-command-summary" className="max-w-3xl break-words text-sm leading-6 text-muted">{r98ReadonlyUiWording.recommendationReviewCommand} It helps operators review manual command review needs, operator coordination, command-level review summaries, high-impact command, blocked paths, incomplete and low-confidence command review signals, revenue continuity command risk, risk-path command risk, escalation command, governance command review, and manual-only command insight. No execution, provider activation, outreach, automation, lead generation, scraping, skip tracing, MLS/public-record behavior, fetch/network behavior, runtime job, polling, persistence, audit writing, or contact is authorized.</p></div>
        <div className="flex max-w-full flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.1em]">{safetyBadges.map((badge) => <span key={badge} className="max-w-full break-words rounded-full border border-border bg-white px-3 py-1 text-center leading-5 text-primary">{badge}</span>)}</div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{commandSignals.map((item) => <article key={item.title} className="min-w-0 rounded-2xl border border-border bg-white p-4"><h3 className="break-words text-sm font-semibold text-primary">{item.title}</h3><p className="mt-2 break-words text-sm font-medium text-primary">{item.status}</p><p className="mt-1 break-words text-sm leading-6 text-muted">{item.detail}</p></article>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Advisory command categories</h3><div className="mt-3 flex max-w-full flex-wrap gap-2">{r98AdvisoryCommandCategories.map((category) => <span key={category} className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 text-xs font-bold leading-5 text-blue-950">{formatCategory(category)}</span>)}</div></div><div className="min-w-0 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><h3 className="break-words font-semibold text-blue-950">Command drift boundary</h3><ul className="mt-2 list-disc space-y-1 pl-5">{r98BlockedDriftTransitions.slice(0, 7).map((transition) => <li key={transition} className="break-words">{transition}</li>)}</ul></div></div>
      <div className="mt-4 flex max-w-full flex-wrap gap-2 text-xs font-bold"><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">readOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">advisoryOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">simulationOnly:true</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerCalled:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">sent:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">persistenceAllowedNow:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">pollingAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">runtimeActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">providerActivationAllowed:false</span><span className="max-w-full break-words rounded border border-blue-200 bg-white px-2 py-1 leading-5 text-blue-950">approvalGrantsExecution:false</span></div>
    </section>
  );
}
