export const defaultExecutiveDirectives = [
  {
    directiveKey: "campaign-001",
    title: "Campaign 001: Inherited Property in Oklahoma",
    summary: "Campaign 001 is the first activation candidate and should be reviewed before any department draft workflow begins.",
    objective: "Generate qualified seller leads by educating Oklahoma homeowners about inherited property decisions.",
    businessGoal: "qualified_seller_lead_generation",
    sourceDepartment: "Executive AI",
    assignedDepartments: ["Marketing", "Sales", "AI COO"],
    requestedOutputs: ["manual_campaign_plan", "sales_follow_up_guidance", "executive_brief_reference"],
    riskLevel: "medium",
    priority: "high",
    expectedBusinessValue: "Create a governed first revenue campaign candidate with source-attributed seller education.",
    governanceNotes: [
      "Internal approval only.",
      "No publishing, sending, scraping, provider calls, ads, outreach, or external workflow execution.",
    ],
    tags: ["High ROI", "Strong brand value", "Urgent revenue opportunity", "Low risk"],
    source: "company_orchestrator_directive_registry",
    assumptions: ["Recommendation only; no workflow state changes or external execution are performed."],
  },
  {
    directiveKey: "brand-readiness-review",
    title: "Brand Readiness Review",
    summary: "This directive can improve activation readiness, but it should remain blocked until the CEO chooses the next priority.",
    objective: "Improve public trust and brand consistency before larger campaign volume.",
    businessGoal: "activation_readiness",
    sourceDepartment: "Executive AI",
    assignedDepartments: ["Marketing", "Executive"],
    requestedOutputs: ["brand_readiness_notes"],
    riskLevel: "low",
    priority: "normal",
    expectedBusinessValue: "Reduce friction before scaling revenue campaigns.",
    governanceNotes: ["Internal approval only.", "No publishing or provider execution."],
    tags: ["Timing", "Dependency missing", "Awaiting outcome data"],
    source: "company_orchestrator_directive_registry",
    assumptions: ["Recommendation only; no workflow state changes or external execution are performed."],
  },
  {
    directiveKey: "content-refresh-review",
    title: "Content Refresh Review",
    summary: "This directive can improve activation readiness, but it should remain blocked until the CEO chooses the next priority.",
    objective: "Identify existing educational content that can be refreshed to support qualified seller lead generation.",
    businessGoal: "content_readiness",
    sourceDepartment: "Executive AI",
    assignedDepartments: ["Marketing", "Knowledge"],
    requestedOutputs: ["content_refresh_candidates"],
    riskLevel: "low",
    priority: "normal",
    expectedBusinessValue: "Reuse approved knowledge before creating new campaign assets.",
    governanceNotes: ["Internal approval only.", "No publishing or provider execution."],
    tags: ["Content reuse", "Needs review", "Manual only"],
    source: "company_orchestrator_directive_registry",
    assumptions: ["Recommendation only; no workflow state changes or external execution are performed."],
  },
  {
    directiveKey: "lead-source-quality-review",
    title: "Lead Source Quality Review",
    summary: "This directive improves revenue data quality before larger activation volume.",
    objective: "Confirm source attribution standards before campaign and seller follow-up learning is reused.",
    businessGoal: "source_quality",
    sourceDepartment: "Executive AI",
    assignedDepartments: ["Sales", "Operations", "Knowledge"],
    requestedOutputs: ["source_quality_review"],
    riskLevel: "low",
    priority: "normal",
    expectedBusinessValue: "Improve conversion learning by keeping lead source attribution clean.",
    governanceNotes: ["Internal approval only.", "No enrichment, scraping, provider calls, or outreach."],
    tags: ["Data quality", "Revenue learning", "Manual review"],
    source: "company_orchestrator_directive_registry",
    assumptions: ["Recommendation only; no workflow state changes or external execution are performed."],
  },
] as const;

export type DefaultExecutiveDirective = (typeof defaultExecutiveDirectives)[number];
