import { postX10ReviewFlags } from "./post-x10-system-operational-review";

export const postX10FuturePlanningAreas = ["controlled provider activation", "communication activation", "human approval execution workflow", "staged rollout strategy", "internal pilot strategy", "limited operator testing", "production safety sequencing", "accessibility expansion", "mobile/PWA readiness", "future D4D integration", "multi-business infrastructure reuse"] as const;

export type PostX10FutureActivationStrategyInput = Partial<Record<"providerActivationPlanned" | "communicationActivationPlanned" | "humanApprovalWorkflowPlanned" | "stagedRolloutPlanned" | "internalPilotPlanned" | "operatorTestingPlanned" | "productionSafetyPlanned" | "accessibilityExpansionPlanned" | "mobilePwaPlanned" | "d4dIntegrationPlanned" | "multiBusinessReusePlanned", boolean>> & Partial<Record<"activateNowRequested" | "providerBuildRequested" | "sendingBuildRequested" | "automationBuildRequested" | "deploymentRequested", boolean>>;
export type PostX10FutureActivationStrategyStatus = "post_x10_strategy_blocked" | "operator_review_required" | "post_x10_strategy_review_clear";

const requiredPlanningAreas: Array<[keyof PostX10FutureActivationStrategyInput, string]> = [["providerActivationPlanned", "controlled provider activation"], ["communicationActivationPlanned", "communication activation"], ["humanApprovalWorkflowPlanned", "human approval execution workflow"], ["stagedRolloutPlanned", "staged rollout strategy"], ["internalPilotPlanned", "internal pilot strategy"], ["operatorTestingPlanned", "limited operator testing"], ["productionSafetyPlanned", "production safety sequencing"], ["accessibilityExpansionPlanned", "accessibility expansion"], ["mobilePwaPlanned", "mobile/PWA readiness"], ["d4dIntegrationPlanned", "future D4D integration"], ["multiBusinessReusePlanned", "multi-business infrastructure reuse"]];
const blockedRequests: Array<[keyof PostX10FutureActivationStrategyInput, string]> = [["activateNowRequested", "activation remains blocked during strategy review"], ["providerBuildRequested", "provider builds remain blocked during strategy review"], ["sendingBuildRequested", "sending builds remain blocked during strategy review"], ["automationBuildRequested", "automation builds remain blocked during strategy review"], ["deploymentRequested", "deployment remains blocked during strategy review"]];

export function createPostX10FutureActivationStrategyReview(input: PostX10FutureActivationStrategyInput = {}) {
  const missingPlanningAreas = requiredPlanningAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: PostX10FutureActivationStrategyStatus = blockedReasons.length > 0 ? "post_x10_strategy_blocked" : missingPlanningAreas.length > 0 ? "operator_review_required" : "post_x10_strategy_review_clear";
  return { phase: "POST-X10E" as const, status, flags: postX10ReviewFlags, planningAreas: postX10FuturePlanningAreas, recommendations: ["Future activation must be separately scoped and staged.", "Provider and communication activation should require human approval workflow maturity first.", "Accessibility/mobile readiness and limited operator testing should precede production safety sequencing."], missingPlanningAreas, blockedReasons };
}
