import { classifyR90ControlledRevenueRecoveryDangerousWording, createR90ControlledRevenueRecoveryDriftRiskAudit, summarizeR90ControlledRevenueRecoveryDriftRiskAudit } from "./r90-controlled-revenue-recovery-drift-risk-audit";

const reviewedInput = { revenueRecoveryExecutionReviewed: true, recoveryGuidanceAutomationReviewed: true, delayedOpportunityOutreachReviewed: true, stalledOpportunityProviderReviewed: true, throughputStabilizationRuntimeReviewed: true, recoveryCoordinationProviderReviewed: true, escalationReviewContactReviewed: true, missingDataSkipTracingReviewed: true, blockedRecoveryScrapingReviewed: true, highImpactLeadCreationReviewed: true, operatorGuidanceProviderReviewed: true, externalApiReviewed: true, fetchNetworkReviewed: true, persistenceReviewed: true, auditWritingReviewed: true, dangerousWordingReviewed: true, accessibilityReviewed: true } as const;

describe("R90B controlled revenue recovery drift risk audit", () => {
  it("defaults to operator review required", () => { const result = createR90ControlledRevenueRecoveryDriftRiskAudit(); expect(result.status).toBe("operator_review_required"); expect(result.riskCategories).toContain("revenue-recovery-to-execution drift"); });
  it("smoke-tests a clear drift audit", () => { const result = createR90ControlledRevenueRecoveryDriftRiskAudit(reviewedInput); expect(result.status).toBe("controlled_revenue_recovery_drift_audit_clear"); expect(result.flags.providerActivationAllowed).toBe(false); });
  it("detects dangerous wording", () => { expect(classifyR90ControlledRevenueRecoveryDangerousWording("execute revenue recovery")).toBe("dangerous_wording_detected"); expect(classifyR90ControlledRevenueRecoveryDangerousWording("manual recovery review recommended")).toBe("wording_clear"); });
  it("pressure-tests all required drift paths as blocked", () => { const result = createR90ControlledRevenueRecoveryDriftRiskAudit({ ...reviewedInput, executionRequested: true, automationRequested: true, outreachRequested: true, providerRequested: true, runtimeRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, externalApiRequested: true, fetchNetworkRequested: true, persistenceRequested: true, auditWritingRequested: true, dangerousWordingRequested: true }); expect(result.status).toBe("controlled_revenue_recovery_drift_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["revenue recovery visibility cannot execute", "recovery guidance cannot become automation", "throughput stabilization cannot trigger runtime jobs", "fetch/network drift remains blocked"])); });
  it("preserves accessibility risk checks", () => { const result = createR90ControlledRevenueRecoveryDriftRiskAudit(reviewedInput); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.accessibility.noMotionDependency).toBe(true); expect(result.accessibility.visibleGovernanceWarnings).toBe(true); });
  it("summarizes drift boundaries", () => { const result = createR90ControlledRevenueRecoveryDriftRiskAudit(reviewedInput); expect(summarizeR90ControlledRevenueRecoveryDriftRiskAudit(result)).toMatch(/revenue recovery, recovery guidance/i); });
});
