import { createR90ControlledRevenueRecoveryReadonlyUiScopeContract, summarizeR90ControlledRevenueRecoveryReadonlyUiScope } from "./r90-controlled-revenue-recovery-readonly-ui-scope-contract";
const reviewedInput = { authorizedSurfacesReviewed: true, revenueRecoveryWordingReviewed: true, delayedOpportunityWordingReviewed: true, stalledRecoverableWordingReviewed: true, throughputStabilizationWordingReviewed: true, manualRecoveryCoordinationWordingReviewed: true, operationalResilienceWordingReviewed: true, escalationWordingReviewed: true, manualReviewWordingReviewed: true, governanceWordingReviewed: true, noExecutionWordingReviewed: true, noProviderWordingReviewed: true, noContactWordingReviewed: true, forbiddenControlsReviewed: true, accessibilityReviewed: true } as const;
describe("R90C controlled revenue recovery readonly UI scope contract", () => {
  it("defaults to operator review required", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract(); expect(result.status).toBe("operator_review_required"); expect(result.authorizedSurfaces).toContain("components/dashboard/controlled-revenue-recovery-summary.tsx"); });
  it("smoke-tests read-only UI scope readiness", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract(reviewedInput); expect(result.status).toBe("controlled_revenue_recovery_ui_scope_ready"); expect(result.flags.readOnly).toBe(true); expect(result.flags.advisoryOnly).toBe(true); expect(result.flags.implementationAllowedNow).toBe(false); });
  it("keeps wording advisory and non-executing", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract(reviewedInput); expect(result.wording.revenueRecovery).toMatch(/advisory visibility only/i); expect(result.wording.manualRecoveryCoordination).toMatch(/Human recovery coordination required/i); expect(result.wording.noExecution).toMatch(/No execution is authorized/i); expect(result.wording.noProvider).toMatch(/No provider activation permitted/i); });
  it("pressure-tests forbidden UI controls", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract({ ...reviewedInput, buttonRequested: true, formRequested: true, inputRequested: true, linkRequested: true, clickHandlerRequested: true, executionControlRequested: true, providerControlRequested: true, outreachControlRequested: true, automationControlRequested: true, runtimeControlRequested: true, fetchNetworkRequested: true, persistenceRequested: true, auditWritingRequested: true }); expect(result.status).toBe("controlled_revenue_recovery_ui_scope_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["buttons remain forbidden", "links remain forbidden", "provider controls remain forbidden", "audit writing remains blocked"])); });
  it("preserves accessibility requirements", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract(reviewedInput); expect(result.accessibility.ariaLabelledby).toBe(true); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.accessibility.visibleGovernanceWarnings).toBe(true); });
  it("summarizes read-only scope", () => { const result = createR90ControlledRevenueRecoveryReadonlyUiScopeContract(reviewedInput); expect(summarizeR90ControlledRevenueRecoveryReadonlyUiScope(result)).toMatch(/read-only advisory wording/i); });
});
