import { createR90ControlledRevenueRecoverySafetyAccessibilityReview, summarizeR90ControlledRevenueRecoverySafetyReview } from "./r90-controlled-revenue-recovery-safety-accessibility-review";
const reviewedInput = { revenueRecoveryExecutionReviewed: true, recoveryGuidanceAutomationReviewed: true, delayedOpportunityOutreachReviewed: true, stalledOpportunityProviderReviewed: true, throughputStabilizationRuntimeReviewed: true, recoveryCoordinationProviderReviewed: true, escalationReviewContactReviewed: true, missingDataSkipTracingReviewed: true, blockedRecoveryScrapingReviewed: true, highImpactLeadCreationReviewed: true, providerPersistenceRuntimeReviewed: true, auditWritingReviewed: true, externalApiFetchEnvReviewed: true, accessibilityReviewed: true, governanceWarningsReviewed: true } as const;
describe("R90E controlled revenue recovery safety accessibility review", () => {
  it("defaults to operator review required", () => { const result = createR90ControlledRevenueRecoverySafetyAccessibilityReview(); expect(result.status).toBe("operator_review_required"); expect(result.findings).toContain("Revenue recovery visibility does not imply execution."); });
  it("smoke-tests a clear safety review", () => { const result = createR90ControlledRevenueRecoverySafetyAccessibilityReview(reviewedInput); expect(result.status).toBe("controlled_revenue_recovery_safety_clear"); expect(result.flags.readOnly).toBe(true); expect(result.flags.advisoryOnly).toBe(true); expect(result.flags.simulationOnly).toBe(true); expect(result.accessibility.semanticStructurePreserved).toBe(true); });
  it("pressure-tests unsafe recovery, provider, runtime, env, and persistence requests as blocked", () => { const result = createR90ControlledRevenueRecoverySafetyAccessibilityReview({ ...reviewedInput, executionRequested: true, automationRequested: true, outreachRequested: true, providerRequested: true, runtimeRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, persistenceRequested: true, pollingRequested: true, auditWritingRequested: true, externalApiRequested: true, fetchNetworkRequested: true, processEnvRequested: true }); expect(result.status).toBe("controlled_revenue_recovery_safety_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["revenue recovery visibility cannot execute", "recovery guidance cannot trigger automation", "throughput stabilization cannot activate runtime jobs", "process.env remains blocked"])); });
  it("preserves accessibility, readable labels, and governance warnings", () => { const result = createR90ControlledRevenueRecoverySafetyAccessibilityReview(reviewedInput); expect(result.accessibility.readableLabelsPreserved).toBe(true); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.accessibility.noMotionDependency).toBe(true); expect(result.accessibility.noAutoRefresh).toBe(true); expect(result.accessibility.visibleGovernanceWarnings).toBe(true); });
  it("summarizes safety and accessibility review", () => { const result = createR90ControlledRevenueRecoverySafetyAccessibilityReview(reviewedInput); expect(summarizeR90ControlledRevenueRecoverySafetyReview(result)).toMatch(/recovery-does-not-execute/i); expect(summarizeR90ControlledRevenueRecoverySafetyReview(result)).toMatch(/visible governance warnings/i); });
});
