import { createR90ControlledRevenueRecoveryFinalLockdownContract, summarizeR90ControlledRevenueRecoveryFinalLockdown } from "./r90-controlled-revenue-recovery-final-lockdown-contract";
const reviewedInput = { r90aReviewed: true, r90bReviewed: true, r90cReviewed: true, r90dReviewed: true, r90eReviewed: true, lockdownRulesReviewed: true, accessibilityReviewed: true, operatorReviewCompleted: true } as const;
describe("R90F controlled revenue recovery final lockdown contract", () => {
  it("defaults to operator review required with lockdown enforced", () => { const result = createR90ControlledRevenueRecoveryFinalLockdownContract(); expect(result.status).toBe("operator_review_required"); expect(result.flags.controlledRevenueRecoveryLockdownEnforced).toBe(true); expect(result.rules).toContain("Revenue recovery intelligence never executes."); });
  it("smoke-tests a fully reviewed lockdown", () => { const result = createR90ControlledRevenueRecoveryFinalLockdownContract(reviewedInput); expect(result.status).toBe("controlled_revenue_recovery_lockdown_enforced"); expect(result.phase).toBe("R90F"); expect(result.nextPhase).toBe("R91 - Revenue Resilience & Stabilization Readiness"); });
  it("preserves all non-execution flags", () => { const result = createR90ControlledRevenueRecoveryFinalLockdownContract(reviewedInput); expect(result.flags.readOnly).toBe(true); expect(result.flags.advisoryOnly).toBe(true); expect(result.flags.simulationOnly).toBe(true); expect(result.flags.providerCalled).toBe(false); expect(result.flags.sent).toBe(false); expect(result.flags.persistenceAllowedNow).toBe(false); expect(result.flags.pollingAllowed).toBe(false); expect(result.flags.runtimeActivationAllowed).toBe(false); expect(result.flags.providerActivationAllowed).toBe(false); expect(result.flags.approvalGrantsExecution).toBe(false); expect(result.flags.executionAllowed).toBe(false); });
  it("pressure-tests every forbidden request as blocked", () => { const result = createR90ControlledRevenueRecoveryFinalLockdownContract({ ...reviewedInput, executionRequested: true, recoveryAutomationRequested: true, outreachRequested: true, providerActivationRequested: true, throughputRuntimeRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, externalApiRequested: true, fetchNetworkRequested: true, pollingRequested: true, persistenceRequested: true, auditWritingRequested: true }); expect(result.status).toBe("controlled_revenue_recovery_lockdown_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["revenue recovery intelligence never executes", "recovery guidance never activates automation", "delayed opportunities never trigger outreach", "throughput stabilization never activates runtime jobs", "high-impact recovery visibility never creates leads"])); });
  it("summarizes the final lockdown", () => { const result = createR90ControlledRevenueRecoveryFinalLockdownContract(reviewedInput); expect(summarizeR90ControlledRevenueRecoveryFinalLockdown(result)).toMatch(/revenue recovery intelligence never executes/i); expect(summarizeR90ControlledRevenueRecoveryFinalLockdown(result)).toMatch(/throughput stabilization never activates runtime jobs/i); expect(summarizeR90ControlledRevenueRecoveryFinalLockdown(result)).toMatch(/execution remains blocked/i); });
});
