import { classifyR91RevenueResilienceStabilizationDangerousWording, createR91RevenueResilienceStabilizationDriftRiskAudit, summarizeR91RevenueResilienceStabilizationDriftRiskAudit } from "./r91-revenue-resilience-stabilization-drift-risk-audit";
const reviewedInput = { stabilizationExecutionReviewed: true, resilienceGuidanceAutomationReviewed: true, revenueContinuityRuntimeReviewed: true, fragilePathProviderReviewed: true, pipelineHealthOutreachReviewed: true, escalationReviewContactReviewed: true, stalledHealthRiskProviderReviewed: true, missingDataSkipTracingReviewed: true, blockedStabilityScrapingReviewed: true, highImpactLeadCreationReviewed: true, operatorGuidanceProviderReviewed: true, externalApiReviewed: true, fetchNetworkReviewed: true, persistenceReviewed: true, auditWritingReviewed: true, dangerousWordingReviewed: true, accessibilityReviewed: true } as const;
describe("R91B revenue resilience stabilization drift risk audit", () => {
  it("defaults to operator review required", () => { const result = createR91RevenueResilienceStabilizationDriftRiskAudit(); expect(result.status).toBe("operator_review_required"); expect(result.riskCategories).toContain("stabilization-to-execution drift"); });
  it("smoke-tests a clear drift audit", () => { const result = createR91RevenueResilienceStabilizationDriftRiskAudit(reviewedInput); expect(result.status).toBe("revenue_resilience_stabilization_drift_audit_clear"); expect(result.flags.providerActivationAllowed).toBe(false); });
  it("detects dangerous wording", () => { expect(classifyR91RevenueResilienceStabilizationDangerousWording("execute stabilization")).toBe("dangerous_wording_detected"); expect(classifyR91RevenueResilienceStabilizationDangerousWording("manual resilience review recommended")).toBe("wording_clear"); });
  it("pressure-tests all required drift paths as blocked", () => { const result = createR91RevenueResilienceStabilizationDriftRiskAudit({ ...reviewedInput, executionRequested: true, automationRequested: true, runtimeRequested: true, providerRequested: true, outreachRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, externalApiRequested: true, fetchNetworkRequested: true, persistenceRequested: true, auditWritingRequested: true, dangerousWordingRequested: true }); expect(result.status).toBe("revenue_resilience_stabilization_drift_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["stabilization visibility cannot execute", "resilience guidance cannot become automation", "revenue continuity visibility cannot activate runtime jobs", "fetch/network drift remains blocked"])); });
  it("preserves accessibility risk checks", () => { const result = createR91RevenueResilienceStabilizationDriftRiskAudit(reviewedInput); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.accessibility.noMotionDependency).toBe(true); expect(result.accessibility.visibleGovernanceWarnings).toBe(true); });
  it("summarizes drift boundaries", () => { const result = createR91RevenueResilienceStabilizationDriftRiskAudit(reviewedInput); expect(summarizeR91RevenueResilienceStabilizationDriftRiskAudit(result)).toMatch(/stabilization, resilience guidance/i); });
});
