import { createR91RevenueResilienceStabilizationScopeContract, summarizeR91RevenueResilienceStabilizationScope } from "./r91-revenue-resilience-stabilization-scope-contract";
const reviewedInput = { revenueResilienceReviewed: true, stabilizationReadinessReviewed: true, pipelineContinuityReviewed: true, manualResiliencePlanningReviewed: true, revenueHealthVisibilityReviewed: true, stabilizationDoesNotExecuteReviewed: true, stabilizationDoesNotContactReviewed: true, stabilizationDoesNotCreateLeadsReviewed: true, noProviderReviewed: true, noRuntimeReviewed: true, noPersistenceReviewed: true, noAuditWritingReviewed: true, accessibilityReviewed: true, deterministicInvariantsReviewed: true, failClosedReviewed: true } as const;
describe("R91A revenue resilience stabilization scope contract", () => {
  it("defaults to operator review required", () => { const result = createR91RevenueResilienceStabilizationScopeContract(); expect(result.status).toBe("operator_review_required"); expect(result.missingReviewAreas).toContain("revenue resilience doctrine"); });
  it("smoke-tests advisory-only stabilization readiness", () => { const result = createR91RevenueResilienceStabilizationScopeContract(reviewedInput); expect(result.status).toBe("revenue_resilience_stabilization_scope_ready"); expect(result.flags.readOnly).toBe(true); expect(result.flags.advisoryOnly).toBe(true); expect(result.flags.simulationOnly).toBe(true); expect(result.flags.providerActivationAllowed).toBe(false); expect(result.flags.approvalGrantsExecution).toBe(false); });
  it("defines deterministic advisory stability categories", () => { const result = createR91RevenueResilienceStabilizationScopeContract(reviewedInput); expect(result.advisoryStabilityCategories).toEqual(expect.arrayContaining(["resilience-review-needed", "stabilization-review-needed", "revenue-continuity-risk", "pipeline-health-review", "manual-only-stability-insight", "advisory-resilience-visibility-only"])); });
  it("pressure-tests forbidden stabilization, provider, sourcing, runtime, and execution paths", () => { const result = createR91RevenueResilienceStabilizationScopeContract({ ...reviewedInput, executionRequested: true, providerRequested: true, outreachRequested: true, runtimeRequested: true, automationRequested: true, leadGenerationRequested: true, scrapingRequested: true, skipTracingRequested: true, mlsPublicRecordRequested: true, fetchNetworkRequested: true, processEnvRequested: true, prismaWriteRequested: true, dbWriteRequested: true, persistenceRequested: true, auditWritingRequested: true }); expect(result.status).toBe("revenue_resilience_stabilization_scope_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["revenue resilience stabilization cannot execute", "provider calls remain blocked", "fetch/network remains blocked", "process.env remains blocked"])); });
  it("preserves accessibility and governance boundaries", () => { const result = createR91RevenueResilienceStabilizationScopeContract(reviewedInput); expect(result.accessibility.semanticHeadings).toBe(true); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.governanceBoundary.stabilityVisibilityOnlyMeans).toContain("execution remains blocked"); });
  it("summarizes revenue resilience stabilization scope", () => { const result = createR91RevenueResilienceStabilizationScopeContract(reviewedInput); expect(summarizeR91RevenueResilienceStabilizationScope(result)).toMatch(/manual-review-only/i); expect(summarizeR91RevenueResilienceStabilizationScope(result)).toMatch(/execution remain blocked/i); });
});
