import { createR92RevenueRiskEarlyWarningSafetyAccessibilityReview, summarizeR92RevenueRiskEarlyWarningSafetyReview } from "./r92-revenue-risk-early-warning-safety-accessibility-review";

const reviewedInput = { riskEarlyWarningExecutionReviewed: true, riskGuidanceAutomationReviewed: true, earlyWarningRuntimeReviewed: true, fragilePipelineProviderReviewed: true, riskSignalOutreachReviewed: true, escalationReviewContactReviewed: true, delayedWorkflowRiskProviderReviewed: true, missingDataSkipTracingReviewed: true, riskPathScrapingReviewed: true, highImpactLeadCreationReviewed: true, providerPersistenceRuntimeReviewed: true, auditWritingReviewed: true, externalApiFetchEnvReviewed: true, accessibilityReviewed: true, governanceWarningsReviewed: true } as const;

describe("R92E revenue risk early warning safety accessibility review", () => {
  it("defaults to operator review required", () => { const result = createR92RevenueRiskEarlyWarningSafetyAccessibilityReview(); expect(result.status).toBe("operator_review_required"); expect(result.missingReviewAreas).toContain("risk early warning visibility does not imply execution"); });
  it("clears deterministic safety review when all areas are reviewed", () => { const result = createR92RevenueRiskEarlyWarningSafetyAccessibilityReview(reviewedInput); expect(result.status).toBe("revenue_risk_early_warning_safety_clear"); expect(result.flags.readOnly).toBe(true); expect(result.flags.providerActivationAllowed).toBe(false); });
  it("blocks execution, provider, outreach, sourcing, persistence, and audit drift", () => { const result = createR92RevenueRiskEarlyWarningSafetyAccessibilityReview({ ...reviewedInput, executionRequested: true, automationRequested: true, runtimeRequested: true, providerRequested: true, outreachRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, persistenceRequested: true, pollingRequested: true, auditWritingRequested: true, externalApiRequested: true, fetchNetworkRequested: true, processEnvRequested: true }); expect(result.status).toBe("revenue_risk_early_warning_safety_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["risk early warning visibility cannot execute", "risk guidance cannot trigger automation", "fragile pipeline signals and delayed workflow risk cannot activate providers", "fetch/network remains blocked"])); });
  it("preserves inclusive accessibility findings", () => { const result = createR92RevenueRiskEarlyWarningSafetyAccessibilityReview(reviewedInput); expect(result.accessibility.semanticHeadingsPreserved).toBe(true); expect(result.accessibility.noColorOnlyMeaning).toBe(true); expect(result.accessibility.noAutoRefresh).toBe(true); expect(result.findings).toContain("Semantic accessibility, readable labels, no color-only meaning, no motion dependency, no auto-refresh, and visible governance warnings are required."); });
  it("summarizes safety boundaries", () => { const result = createR92RevenueRiskEarlyWarningSafetyAccessibilityReview(reviewedInput); expect(summarizeR92RevenueRiskEarlyWarningSafetyReview(result)).toMatch(/risk-early-warning-does-not-execute/i); });
});
