import { createR92RevenueRiskEarlyWarningFinalLockdownContract, summarizeR92RevenueRiskEarlyWarningFinalLockdown } from "./r92-revenue-risk-early-warning-final-lockdown-contract";

const reviewedInput = { r92aReviewed: true, r92bReviewed: true, r92cReviewed: true, r92dReviewed: true, r92eReviewed: true, lockdownRulesReviewed: true, accessibilityReviewed: true, operatorReviewCompleted: true } as const;

describe("R92F revenue risk early warning final lockdown contract", () => {
  it("defaults to operator review required", () => { const result = createR92RevenueRiskEarlyWarningFinalLockdownContract(); expect(result.status).toBe("operator_review_required"); expect(result.missingReviewAreas).toContain("R92A scope contract reviewed"); });
  it("enforces final lockdown after all reviews", () => { const result = createR92RevenueRiskEarlyWarningFinalLockdownContract(reviewedInput); expect(result.status).toBe("revenue_risk_early_warning_lockdown_enforced"); expect(result.flags.revenueRiskEarlyWarningLockdownEnforced).toBe(true); expect(result.flags.readOnly).toBe(true); expect(result.nextPhase).toBe("R93 - Revenue Risk Review Command Readiness"); });
  it("locks every execution, provider, outreach, sourcing, runtime, persistence, and audit path", () => { const result = createR92RevenueRiskEarlyWarningFinalLockdownContract({ ...reviewedInput, executionRequested: true, riskGuidanceAutomationRequested: true, earlyWarningRuntimeRequested: true, providerActivationRequested: true, outreachRequested: true, contactRequested: true, skipTracingRequested: true, scrapingRequested: true, leadCreationRequested: true, externalApiRequested: true, fetchNetworkRequested: true, pollingRequested: true, persistenceRequested: true, auditWritingRequested: true }); expect(result.status).toBe("revenue_risk_early_warning_lockdown_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["revenue risk intelligence never executes", "risk guidance never activates automation", "early-warning signals never activate runtime jobs", "fetch/network behavior remains blocked"])); });
  it("declares explicit final rules", () => { const result = createR92RevenueRiskEarlyWarningFinalLockdownContract(reviewedInput); expect(result.rules).toEqual(expect.arrayContaining(["Revenue risk intelligence never executes.", "Risk signals never trigger outreach.", "Execution remains blocked."])); });
  it("summarizes the lockdown", () => { const result = createR92RevenueRiskEarlyWarningFinalLockdownContract(reviewedInput); expect(summarizeR92RevenueRiskEarlyWarningFinalLockdown(result)).toMatch(/execution remains blocked/i); });
});
