import { createR92RevenueRiskEarlyWarningReadonlyUiScopeContract, summarizeR92RevenueRiskEarlyWarningReadonlyUiScope } from "./r92-revenue-risk-early-warning-readonly-ui-scope-contract";

const reviewedInput = { authorizedSurfacesReviewed: true, earlyWarningWordingReviewed: true, revenueRiskWordingReviewed: true, pipelineFragilityWordingReviewed: true, delayedWorkflowRiskWordingReviewed: true, revenueContinuityThreatWordingReviewed: true, manualRiskReviewWordingReviewed: true, escalationWordingReviewed: true, governanceWordingReviewed: true, noExecutionWordingReviewed: true, noProviderWordingReviewed: true, noContactWordingReviewed: true, forbiddenControlsReviewed: true, accessibilityReviewed: true } as const;

describe("R92C revenue risk early warning read-only UI scope contract", () => {
  it("defaults to operator review required", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract(); expect(result.status).toBe("operator_review_required"); expect(result.missingReviewAreas).toContain("authorized read-only surfaces"); });
  it("authorizes only read-only surfaces", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract(reviewedInput); expect(result.status).toBe("revenue_risk_early_warning_ui_scope_ready"); expect(result.authorizedSurfaces).toContain("components/dashboard/revenue-risk-early-warning-summary.tsx"); expect(result.authorizedSurfaces).toContain("app/(dashboard)/dashboard/page.tsx"); });
  it("keeps wording advisory, manual, and non-contacting", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract(reviewedInput); expect(result.wording.earlyWarning).toMatch(/advisory visibility only/i); expect(result.wording.manualRiskReview).toMatch(/manual risk review recommended/i); expect(result.wording.noExecution).toMatch(/No execution/i); expect(result.wording.noProvider).toMatch(/No provider/i); expect(result.wording.noContact).toMatch(/No buyer, seller/i); });
  it("blocks forbidden UI controls and behavior", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract({ ...reviewedInput, buttonRequested: true, formRequested: true, inputRequested: true, linkRequested: true, clickHandlerRequested: true, providerControlRequested: true, executionControlRequested: true, fetchNetworkRequested: true, persistenceRequested: true, auditWritingRequested: true }); expect(result.status).toBe("revenue_risk_early_warning_ui_scope_blocked"); expect(result.blockedReasons).toEqual(expect.arrayContaining(["buttons remain forbidden", "links remain forbidden", "provider controls remain forbidden", "fetch/network remains blocked"])); });
  it("preserves accessible read-only UI requirements", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract(reviewedInput); expect(result.accessibility.semanticHeadings).toBe(true); expect(result.accessibility.textBasedStatusMeaning).toBe(true); expect(result.accessibility.noAutoRefresh).toBe(true); });
  it("summarizes UI scope", () => { const result = createR92RevenueRiskEarlyWarningReadonlyUiScopeContract(reviewedInput); expect(summarizeR92RevenueRiskEarlyWarningReadonlyUiScope(result)).toMatch(/early warning, revenue risk/i); });
});
