import { x1AccessibilityRequirements, x1CommandCenterFlags } from "./x1-human-operational-command-center-scope-contract";

export type X1SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "routingReviewed" | "outreachReviewed" | "contactReviewed" | "providerReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "leadCreationReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "routingRequested" | "outreachRequested" | "contactRequested" | "providerRequested" | "runtimeRequested" | "skipTracingRequested" | "leadCreationRequested" | "persistenceRequested" | "auditWritingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X1SafetyStatus = "x1_final_lockdown_blocked" | "operator_review_required" | "x1_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X1SafetyInput, string]> = [["executionReviewed", "command center does not execute"], ["automationReviewed", "next-best-action does not automate"], ["routingReviewed", "focus items do not route work"], ["outreachReviewed", "overdue follow-up does not trigger outreach"], ["contactReviewed", "hot seller does not trigger contact"], ["providerReviewed", "buyer-ready does not activate providers"], ["runtimeReviewed", "near-close does not activate runtime jobs"], ["skipTracingReviewed", "missing data does not trigger skip tracing"], ["leadCreationReviewed", "opportunities do not create leads"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X1SafetyInput, string]> = [["executionRequested", "command center cannot execute"], ["automationRequested", "next-best-action cannot automate"], ["routingRequested", "focus items cannot route work"], ["outreachRequested", "overdue follow-up cannot trigger outreach"], ["contactRequested", "hot seller cannot trigger contact"], ["providerRequested", "buyer-ready cannot activate providers"], ["runtimeRequested", "near-close cannot activate runtime jobs"], ["skipTracingRequested", "missing data cannot trigger skip tracing"], ["leadCreationRequested", "opportunities cannot create leads"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX1HumanOperationalCommandCenterSafetyFinalLockdownReview(input: X1SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X1SafetyStatus = blockedReasons.length > 0 ? "x1_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x1_final_lockdown_clear";
  return { phase: "X1F" as const, status, flags: x1CommandCenterFlags, accessibility: x1AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
