import { x1AccessibilityRequirements, x1CommandCenterFlags } from "./x1-human-operational-command-center-scope-contract";

export const x1DriftRiskCategories = ["command-center-to-execution drift", "next-best-action-to-automation drift", "focus-item-to-routing drift", "overdue-follow-up-to-outreach drift", "hot-seller-to-contact drift", "buyer-ready-to-provider drift", "near-close-to-runtime drift", "missing-data-to-skip-tracing drift", "opportunity-to-lead-creation drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x1DangerousWordingPatterns = ["send", "call now", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "verify owner", "skip trace", "scrape records"] as const;
export const x1BlockedDriftTransitions = ["command center cannot execute", "next-best-action cannot automate", "focus items cannot route work", "overdue follow-up cannot trigger outreach", "hot seller cannot trigger contact", "buyer-ready cannot activate providers", "near-close cannot activate runtime jobs", "missing data cannot trigger skip tracing", "opportunities cannot create leads", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X1DriftInput = Partial<Record<"executionReviewed" | "automationReviewed" | "routingReviewed" | "outreachReviewed" | "contactReviewed" | "providerReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "leadCreationReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "routingRequested" | "outreachRequested" | "contactRequested" | "providerRequested" | "runtimeRequested" | "skipTracingRequested" | "leadCreationRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X1DriftStatus = "x1_drift_blocked" | "operator_review_required" | "x1_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X1DriftInput, string]> = [["executionReviewed", "command-center-to-execution drift"], ["automationReviewed", "next-best-action-to-automation drift"], ["routingReviewed", "focus-item-to-routing drift"], ["outreachReviewed", "overdue-follow-up-to-outreach drift"], ["contactReviewed", "hot-seller-to-contact drift"], ["providerReviewed", "buyer-ready-to-provider drift"], ["runtimeReviewed", "near-close-to-runtime drift"], ["skipTracingReviewed", "missing-data-to-skip-tracing drift"], ["leadCreationReviewed", "opportunity-to-lead-creation drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X1DriftInput, string]> = [["executionRequested", "command center cannot execute"], ["automationRequested", "next-best-action cannot automate"], ["routingRequested", "focus items cannot route work"], ["outreachRequested", "overdue follow-up cannot trigger outreach"], ["contactRequested", "hot seller cannot trigger contact"], ["providerRequested", "buyer-ready cannot activate providers"], ["runtimeRequested", "near-close cannot activate runtime jobs"], ["skipTracingRequested", "missing data cannot trigger skip tracing"], ["leadCreationRequested", "opportunities cannot create leads"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX1CommandCenterDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x1DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX1HumanOperationalCommandCenterDriftRiskAudit(input: X1DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X1DriftStatus = blockedReasons.length > 0 ? "x1_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x1_drift_audit_clear";
  return { phase: "X1C" as const, status, flags: x1CommandCenterFlags, riskCategories: x1DriftRiskCategories, blockedDriftTransitions: x1BlockedDriftTransitions, accessibility: x1AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
