import { x10AccessibilityRequirements, x10InternalOperationalPilotFlags } from "./x10-internal-operational-pilot-scope-contract";

export const x10DriftRiskCategories = ["pilot-review-to-execution drift", "readiness-review-to-send drift", "governance-review-to-provider drift", "communication-readiness-to-outreach drift", "provider-blocked-to-provider-activation drift", "execution-blocked-to-runtime drift", "workflow-readiness-to-routing drift", "operational-risk-to-automation drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x10DangerousWordingPatterns = ["send now", "activate live", "auto-send", "execute", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "override governance", "bypass approval", "scrape records"] as const;
export const x10BlockedDriftTransitions = ["pilot review cannot execute", "readiness review cannot send", "governance review cannot activate providers", "communication readiness cannot trigger outreach", "provider-blocked review cannot activate providers", "execution-blocked review cannot activate runtime jobs", "workflow readiness cannot route work", "operational risk cannot activate automation", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked", "production activation remains blocked"] as const;

export type X10DriftInput = Partial<Record<"executionReviewed" | "sendReviewed" | "providerReviewed" | "outreachReviewed" | "providerBlockedReviewed" | "runtimeReviewed" | "routingReviewed" | "automationReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "productionActivationReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "sendRequested" | "providerRequested" | "outreachRequested" | "providerBlockedActivationRequested" | "runtimeRequested" | "routingRequested" | "automationRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "productionActivationRequested" | "dangerousWordingRequested", boolean>>;
export type X10DriftStatus = "x10_drift_blocked" | "operator_review_required" | "x10_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X10DriftInput, string]> = [["executionReviewed", "pilot-review-to-execution drift"], ["sendReviewed", "readiness-review-to-send drift"], ["providerReviewed", "governance-review-to-provider drift"], ["outreachReviewed", "communication-readiness-to-outreach drift"], ["providerBlockedReviewed", "provider-blocked-to-provider-activation drift"], ["runtimeReviewed", "execution-blocked-to-runtime drift"], ["routingReviewed", "workflow-readiness-to-routing drift"], ["automationReviewed", "operational-risk-to-automation drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["productionActivationReviewed", "production activation drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X10DriftInput, string]> = [["executionRequested", "pilot review cannot execute"], ["sendRequested", "readiness review cannot send"], ["providerRequested", "governance review cannot activate providers"], ["outreachRequested", "communication readiness cannot trigger outreach"], ["providerBlockedActivationRequested", "provider-blocked review cannot activate providers"], ["runtimeRequested", "execution-blocked review cannot activate runtime jobs"], ["routingRequested", "workflow readiness cannot route work"], ["automationRequested", "operational risk cannot activate automation"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["productionActivationRequested", "production activation remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX10InternalOperationalPilotDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x10DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX10InternalOperationalPilotDriftRiskAudit(input: X10DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X10DriftStatus = blockedReasons.length > 0 ? "x10_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x10_drift_audit_clear";
  return { phase: "X10C" as const, status, flags: x10InternalOperationalPilotFlags, riskCategories: x10DriftRiskCategories, blockedDriftTransitions: x10BlockedDriftTransitions, accessibility: x10AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
