import { x10AccessibilityRequirements, x10InternalOperationalPilotFlags } from "./x10-internal-operational-pilot-scope-contract";

export type X10SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "sendReviewed" | "providerReviewed" | "outreachReviewed" | "runtimeReviewed" | "providerBlockedReviewed" | "routingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "sendRequested" | "providerRequested" | "outreachRequested" | "runtimeRequested" | "providerBlockedActivationRequested" | "routingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X10SafetyStatus = "x10_final_lockdown_blocked" | "operator_review_required" | "x10_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X10SafetyInput, string]> = [["executionReviewed", "pilot workspace does not execute"], ["automationReviewed", "pilot recommendations do not automate"], ["sendReviewed", "workflow readiness review does not send"], ["providerReviewed", "governance readiness review does not activate providers"], ["outreachReviewed", "communication readiness review does not trigger outreach"], ["runtimeReviewed", "execution-blocked review does not activate runtime"], ["providerBlockedReviewed", "provider-blocked review does not activate providers"], ["routingReviewed", "operational-risk review does not route work"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X10SafetyInput, string]> = [["executionRequested", "pilot workspace cannot execute"], ["automationRequested", "pilot recommendations cannot automate"], ["sendRequested", "workflow readiness cannot send"], ["providerRequested", "governance readiness cannot activate providers"], ["outreachRequested", "communication readiness cannot trigger outreach"], ["runtimeRequested", "execution-blocked review cannot activate runtime"], ["providerBlockedActivationRequested", "provider-blocked review cannot activate providers"], ["routingRequested", "operational-risk review cannot route work"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX10InternalOperationalPilotSafetyFinalLockdownReview(input: X10SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X10SafetyStatus = blockedReasons.length > 0 ? "x10_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x10_final_lockdown_clear";
  return { phase: "X10F" as const, status, flags: x10InternalOperationalPilotFlags, accessibility: x10AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
