import { x2AccessibilityRequirements, x2LeadOperationsFlags } from "./x2-live-manual-lead-operations-scope-contract";

export type X2SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "outreachReviewed" | "contactReviewed" | "providerReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "routingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "outreachRequested" | "contactRequested" | "providerRequested" | "runtimeRequested" | "skipTracingRequested" | "routingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X2SafetyStatus = "x2_final_lockdown_blocked" | "operator_review_required" | "x2_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X2SafetyInput, string]> = [["executionReviewed", "lead operations do not execute"], ["automationReviewed", "workflow recommendations do not automate"], ["outreachReviewed", "follow-up review does not trigger outreach"], ["contactReviewed", "seller-status review does not trigger contact"], ["providerReviewed", "revenue-priority review does not activate providers"], ["runtimeReviewed", "blocked workflow review does not activate runtime jobs"], ["skipTracingReviewed", "missing data review does not trigger skip tracing"], ["routingReviewed", "workload visibility does not route work"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X2SafetyInput, string]> = [["executionRequested", "lead operations cannot execute"], ["automationRequested", "workflow recommendations cannot automate"], ["outreachRequested", "follow-up review cannot trigger outreach"], ["contactRequested", "seller-status review cannot trigger contact"], ["providerRequested", "revenue-priority review cannot activate providers"], ["runtimeRequested", "blocked workflow review cannot activate runtime jobs"], ["skipTracingRequested", "missing data review cannot trigger skip tracing"], ["routingRequested", "workload visibility cannot route work"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX2LiveManualLeadOperationsSafetyFinalLockdownReview(input: X2SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X2SafetyStatus = blockedReasons.length > 0 ? "x2_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x2_final_lockdown_clear";
  return { phase: "X2F" as const, status, flags: x2LeadOperationsFlags, accessibility: x2AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
