import { x2AccessibilityRequirements, x2LeadOperationsFlags } from "./x2-live-manual-lead-operations-scope-contract";

export const x2DriftRiskCategories = ["lead-review-to-execution drift", "follow-up-review-to-outreach drift", "priority-review-to-routing drift", "workload-review-to-automation drift", "revenue-priority-to-provider drift", "seller-status-to-contact drift", "aging-lead-to-autonomous-follow-up drift", "blocked-workflow-to-runtime drift", "missing-data-to-skip-tracing drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x2DangerousWordingPatterns = ["send", "call now", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "verify owner", "skip trace", "scrape records"] as const;
export const x2BlockedDriftTransitions = ["lead review cannot execute", "follow-up review cannot trigger outreach", "priority review cannot route work", "workload review cannot automate", "revenue priority cannot activate providers", "seller status cannot trigger contact", "aging lead cannot create autonomous follow-up", "blocked workflow cannot activate runtime jobs", "missing data cannot trigger skip tracing", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked", "autonomous workflow execution remains blocked"] as const;

export type X2DriftInput = Partial<Record<"executionReviewed" | "outreachReviewed" | "routingReviewed" | "automationReviewed" | "providerReviewed" | "contactReviewed" | "autonomousFollowUpReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "outreachRequested" | "routingRequested" | "automationRequested" | "providerRequested" | "contactRequested" | "autonomousFollowUpRequested" | "runtimeRequested" | "skipTracingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X2DriftStatus = "x2_drift_blocked" | "operator_review_required" | "x2_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X2DriftInput, string]> = [["executionReviewed", "lead-review-to-execution drift"], ["outreachReviewed", "follow-up-review-to-outreach drift"], ["routingReviewed", "priority-review-to-routing drift"], ["automationReviewed", "workload-review-to-automation drift"], ["providerReviewed", "revenue-priority-to-provider drift"], ["contactReviewed", "seller-status-to-contact drift"], ["autonomousFollowUpReviewed", "aging-lead-to-autonomous-follow-up drift"], ["runtimeReviewed", "blocked-workflow-to-runtime drift"], ["skipTracingReviewed", "missing-data-to-skip-tracing drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X2DriftInput, string]> = [["executionRequested", "lead review cannot execute"], ["outreachRequested", "follow-up review cannot trigger outreach"], ["routingRequested", "priority review cannot route work"], ["automationRequested", "workload review cannot automate"], ["providerRequested", "revenue priority cannot activate providers"], ["contactRequested", "seller status cannot trigger contact"], ["autonomousFollowUpRequested", "aging lead cannot create autonomous follow-up"], ["runtimeRequested", "blocked workflow cannot activate runtime jobs"], ["skipTracingRequested", "missing data cannot trigger skip tracing"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX2LeadOperationsDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x2DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX2LiveManualLeadOperationsDriftRiskAudit(input: X2DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X2DriftStatus = blockedReasons.length > 0 ? "x2_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x2_drift_audit_clear";
  return { phase: "X2C" as const, status, flags: x2LeadOperationsFlags, riskCategories: x2DriftRiskCategories, blockedDriftTransitions: x2BlockedDriftTransitions, accessibility: x2AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
