import { x3AccessibilityRequirements, x3SellerConversationFlags } from "./x3-human-guided-seller-conversation-support-scope-contract";

export const x3DriftRiskCategories = ["conversation-guidance-to-contact drift", "follow-up-language-to-message-sending drift", "seller-context-to-provider drift", "offer-readiness-to-execution drift", "seller-objection-to-automation drift", "seller-priority-to-routing drift", "missing-context-to-skip-tracing drift", "seller-research-to-scraping drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x3DangerousWordingPatterns = ["send", "call now", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "verify owner", "skip trace", "scrape records"] as const;
export const x3BlockedDriftTransitions = ["conversation guidance cannot contact sellers", "follow-up language cannot send messages", "seller context cannot activate providers", "offer readiness cannot execute", "seller objections cannot automate", "seller priority cannot route work", "missing context cannot trigger skip tracing", "seller research cannot trigger scraping", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X3DriftInput = Partial<Record<"contactReviewed" | "sendReviewed" | "providerReviewed" | "executionReviewed" | "automationReviewed" | "routingReviewed" | "skipTracingReviewed" | "scrapingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"contactRequested" | "sendRequested" | "providerRequested" | "executionRequested" | "automationRequested" | "routingRequested" | "skipTracingRequested" | "scrapingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X3DriftStatus = "x3_drift_blocked" | "operator_review_required" | "x3_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X3DriftInput, string]> = [["contactReviewed", "conversation-guidance-to-contact drift"], ["sendReviewed", "follow-up-language-to-message-sending drift"], ["providerReviewed", "seller-context-to-provider drift"], ["executionReviewed", "offer-readiness-to-execution drift"], ["automationReviewed", "seller-objection-to-automation drift"], ["routingReviewed", "seller-priority-to-routing drift"], ["skipTracingReviewed", "missing-context-to-skip-tracing drift"], ["scrapingReviewed", "seller-research-to-scraping drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X3DriftInput, string]> = [["contactRequested", "conversation guidance cannot contact sellers"], ["sendRequested", "follow-up language cannot send messages"], ["providerRequested", "seller context cannot activate providers"], ["executionRequested", "offer readiness cannot execute"], ["automationRequested", "seller objections cannot automate"], ["routingRequested", "seller priority cannot route work"], ["skipTracingRequested", "missing context cannot trigger skip tracing"], ["scrapingRequested", "seller research cannot trigger scraping"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX3SellerConversationDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x3DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX3HumanGuidedSellerConversationSupportDriftRiskAudit(input: X3DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X3DriftStatus = blockedReasons.length > 0 ? "x3_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x3_drift_audit_clear";
  return { phase: "X3C" as const, status, flags: x3SellerConversationFlags, riskCategories: x3DriftRiskCategories, blockedDriftTransitions: x3BlockedDriftTransitions, accessibility: x3AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
