import { x3AccessibilityRequirements, x3SellerConversationFlags } from "./x3-human-guided-seller-conversation-support-scope-contract";

export type X3SafetyInput = Partial<Record<"contactReviewed" | "sendReviewed" | "executionReviewed" | "automationReviewed" | "routingReviewed" | "providerReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "scrapingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"contactRequested" | "sendRequested" | "executionRequested" | "automationRequested" | "routingRequested" | "providerRequested" | "runtimeRequested" | "skipTracingRequested" | "scrapingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X3SafetyStatus = "x3_final_lockdown_blocked" | "operator_review_required" | "x3_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X3SafetyInput, string]> = [["contactReviewed", "seller conversation support does not contact"], ["sendReviewed", "conversation guidance does not send messages"], ["executionReviewed", "seller conversation support does not execute"], ["automationReviewed", "seller guidance does not automate"], ["routingReviewed", "seller priority does not route work"], ["providerReviewed", "seller context does not activate providers"], ["runtimeReviewed", "conversation support does not activate runtime jobs"], ["skipTracingReviewed", "missing seller context does not trigger skip tracing"], ["scrapingReviewed", "seller research does not trigger scraping"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X3SafetyInput, string]> = [["contactRequested", "seller conversation support cannot contact"], ["sendRequested", "conversation guidance cannot send messages"], ["executionRequested", "seller conversation support cannot execute"], ["automationRequested", "seller guidance cannot automate"], ["routingRequested", "seller priority cannot route work"], ["providerRequested", "seller context cannot activate providers"], ["runtimeRequested", "conversation support cannot activate runtime jobs"], ["skipTracingRequested", "missing seller context cannot trigger skip tracing"], ["scrapingRequested", "seller research cannot trigger scraping"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX3HumanGuidedSellerConversationSupportSafetyFinalLockdownReview(input: X3SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X3SafetyStatus = blockedReasons.length > 0 ? "x3_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x3_final_lockdown_clear";
  return { phase: "X3F" as const, status, flags: x3SellerConversationFlags, accessibility: x3AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
