import { x4AccessibilityRequirements, x4BuyerMatchingFlags } from "./x4-human-guided-buyer-matching-operations-scope-contract";

export type X4SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "outreachReviewed" | "providerReviewed" | "contactReviewed" | "runtimeReviewed" | "routingReviewed" | "skipTracingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "outreachRequested" | "providerRequested" | "contactRequested" | "runtimeRequested" | "routingRequested" | "skipTracingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X4SafetyStatus = "x4_final_lockdown_blocked" | "operator_review_required" | "x4_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X4SafetyInput, string]> = [["executionReviewed", "buyer operations do not execute"], ["automationReviewed", "buyer recommendations do not automate"], ["outreachReviewed", "buyer-fit review does not trigger outreach"], ["providerReviewed", "assignment-readiness review does not activate providers"], ["contactReviewed", "buyer-demand review does not trigger contact"], ["runtimeReviewed", "disposition review does not activate runtime jobs"], ["routingReviewed", "blocked disposition review does not route work"], ["skipTracingReviewed", "missing buyer data review does not trigger skip tracing"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X4SafetyInput, string]> = [["executionRequested", "buyer operations cannot execute"], ["automationRequested", "buyer recommendations cannot automate"], ["outreachRequested", "buyer-fit review cannot trigger outreach"], ["providerRequested", "assignment-readiness review cannot activate providers"], ["contactRequested", "buyer-demand review cannot trigger contact"], ["runtimeRequested", "disposition review cannot activate runtime jobs"], ["routingRequested", "blocked disposition review cannot route work"], ["skipTracingRequested", "missing buyer data review cannot trigger skip tracing"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX4HumanGuidedBuyerMatchingOperationsSafetyFinalLockdownReview(input: X4SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X4SafetyStatus = blockedReasons.length > 0 ? "x4_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x4_final_lockdown_clear";
  return { phase: "X4F" as const, status, flags: x4BuyerMatchingFlags, accessibility: x4AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
