import { x4AccessibilityRequirements, x4BuyerMatchingFlags } from "./x4-human-guided-buyer-matching-operations-scope-contract";

export const x4DriftRiskCategories = ["buyer-review-to-execution drift", "buyer-fit-to-routing drift", "assignment-review-to-provider drift", "buyer-demand-to-outreach drift", "disposition-review-to-automation drift", "buyer-alignment-to-contact drift", "revenue-throughput-to-runtime drift", "missing-buyer-data-to-skip-tracing drift", "autonomous-assignment drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x4DangerousWordingPatterns = ["send", "blast", "assign automatically", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact buyer", "verify buyer", "skip trace", "scrape records"] as const;
export const x4BlockedDriftTransitions = ["buyer review cannot execute", "buyer fit cannot route work", "assignment review cannot activate providers", "buyer demand cannot trigger outreach", "disposition review cannot automate", "buyer alignment cannot trigger contact", "revenue throughput cannot activate runtime jobs", "missing buyer data cannot trigger skip tracing", "autonomous buyer assignment remains blocked", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X4DriftInput = Partial<Record<"executionReviewed" | "routingReviewed" | "providerReviewed" | "outreachReviewed" | "automationReviewed" | "contactReviewed" | "runtimeReviewed" | "skipTracingReviewed" | "autonomousAssignmentReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "routingRequested" | "providerRequested" | "outreachRequested" | "automationRequested" | "contactRequested" | "runtimeRequested" | "skipTracingRequested" | "autonomousAssignmentRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X4DriftStatus = "x4_drift_blocked" | "operator_review_required" | "x4_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X4DriftInput, string]> = [["executionReviewed", "buyer-review-to-execution drift"], ["routingReviewed", "buyer-fit-to-routing drift"], ["providerReviewed", "assignment-review-to-provider drift"], ["outreachReviewed", "buyer-demand-to-outreach drift"], ["automationReviewed", "disposition-review-to-automation drift"], ["contactReviewed", "buyer-alignment-to-contact drift"], ["runtimeReviewed", "revenue-throughput-to-runtime drift"], ["skipTracingReviewed", "missing-buyer-data-to-skip-tracing drift"], ["autonomousAssignmentReviewed", "autonomous-assignment drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X4DriftInput, string]> = [["executionRequested", "buyer review cannot execute"], ["routingRequested", "buyer fit cannot route work"], ["providerRequested", "assignment review cannot activate providers"], ["outreachRequested", "buyer demand cannot trigger outreach"], ["automationRequested", "disposition review cannot automate"], ["contactRequested", "buyer alignment cannot trigger contact"], ["runtimeRequested", "revenue throughput cannot activate runtime jobs"], ["skipTracingRequested", "missing buyer data cannot trigger skip tracing"], ["autonomousAssignmentRequested", "autonomous buyer assignment remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX4BuyerMatchingDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x4DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX4HumanGuidedBuyerMatchingOperationsDriftRiskAudit(input: X4DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X4DriftStatus = blockedReasons.length > 0 ? "x4_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x4_drift_audit_clear";
  return { phase: "X4C" as const, status, flags: x4BuyerMatchingFlags, riskCategories: x4DriftRiskCategories, blockedDriftTransitions: x4BlockedDriftTransitions, accessibility: x4AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
