import { x5AccessibilityRequirements, x5DealThroughputFlags } from "./x5-deal-throughput-optimization-layer-scope-contract";

export type X5SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "routingReviewed" | "providerReviewed" | "runtimeReviewed" | "outreachReviewed" | "workflowExecutionReviewed" | "skipTracingReviewed" | "scrapingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "routingRequested" | "providerRequested" | "runtimeRequested" | "outreachRequested" | "workflowExecutionRequested" | "skipTracingRequested" | "scrapingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X5SafetyStatus = "x5_final_lockdown_blocked" | "operator_review_required" | "x5_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X5SafetyInput, string]> = [["executionReviewed", "deal throughput optimization does not execute"], ["automationReviewed", "optimization recommendations do not automate"], ["routingReviewed", "stage friction review does not route work"], ["providerReviewed", "assignment-readiness review does not activate providers"], ["runtimeReviewed", "closing-readiness review does not activate runtime jobs"], ["outreachReviewed", "revenue delay review does not trigger outreach"], ["workflowExecutionReviewed", "blocked throughput review does not execute workflow actions"], ["skipTracingReviewed", "missing throughput data does not trigger skip tracing"], ["scrapingReviewed", "throughput research does not trigger scraping"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X5SafetyInput, string]> = [["executionRequested", "deal throughput optimization cannot execute"], ["automationRequested", "optimization recommendations cannot automate"], ["routingRequested", "stage friction review cannot route work"], ["providerRequested", "assignment-readiness review cannot activate providers"], ["runtimeRequested", "closing-readiness review cannot activate runtime jobs"], ["outreachRequested", "revenue delay review cannot trigger outreach"], ["workflowExecutionRequested", "blocked throughput review cannot execute workflow actions"], ["skipTracingRequested", "missing throughput data cannot trigger skip tracing"], ["scrapingRequested", "throughput research cannot trigger scraping"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX5DealThroughputOptimizationLayerSafetyFinalLockdownReview(input: X5SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X5SafetyStatus = blockedReasons.length > 0 ? "x5_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x5_final_lockdown_clear";
  return { phase: "X5F" as const, status, flags: x5DealThroughputFlags, accessibility: x5AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
