import { x5AccessibilityRequirements, x5DealThroughputFlags } from "./x5-deal-throughput-optimization-layer-scope-contract";

export const x5DriftRiskCategories = ["throughput-review-to-execution drift", "optimization-recommendation-to-automation drift", "stage-friction-to-routing drift", "assignment-readiness-to-provider drift", "closing-readiness-to-runtime drift", "revenue-delay-to-outreach drift", "blocked-throughput-to-workflow-execution drift", "missing-throughput-data-to-skip-tracing drift", "throughput-research-to-scraping drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x5DangerousWordingPatterns = ["send", "call now", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact buyer", "contact seller", "skip trace", "scrape records", "optimize automatically"] as const;
export const x5BlockedDriftTransitions = ["throughput review cannot execute", "optimization recommendations cannot automate", "stage friction cannot route work", "assignment readiness cannot activate providers", "closing readiness cannot activate runtime jobs", "revenue delay cannot trigger outreach", "blocked throughput cannot execute workflow", "missing throughput data cannot trigger skip tracing", "throughput research cannot trigger scraping", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X5DriftInput = Partial<Record<"executionReviewed" | "automationReviewed" | "routingReviewed" | "providerReviewed" | "runtimeReviewed" | "outreachReviewed" | "workflowExecutionReviewed" | "skipTracingReviewed" | "scrapingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "routingRequested" | "providerRequested" | "runtimeRequested" | "outreachRequested" | "workflowExecutionRequested" | "skipTracingRequested" | "scrapingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X5DriftStatus = "x5_drift_blocked" | "operator_review_required" | "x5_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X5DriftInput, string]> = [["executionReviewed", "throughput-review-to-execution drift"], ["automationReviewed", "optimization-recommendation-to-automation drift"], ["routingReviewed", "stage-friction-to-routing drift"], ["providerReviewed", "assignment-readiness-to-provider drift"], ["runtimeReviewed", "closing-readiness-to-runtime drift"], ["outreachReviewed", "revenue-delay-to-outreach drift"], ["workflowExecutionReviewed", "blocked-throughput-to-workflow-execution drift"], ["skipTracingReviewed", "missing-throughput-data-to-skip-tracing drift"], ["scrapingReviewed", "throughput-research-to-scraping drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X5DriftInput, string]> = [["executionRequested", "throughput review cannot execute"], ["automationRequested", "optimization recommendations cannot automate"], ["routingRequested", "stage friction cannot route work"], ["providerRequested", "assignment readiness cannot activate providers"], ["runtimeRequested", "closing readiness cannot activate runtime jobs"], ["outreachRequested", "revenue delay cannot trigger outreach"], ["workflowExecutionRequested", "blocked throughput cannot execute workflow"], ["skipTracingRequested", "missing throughput data cannot trigger skip tracing"], ["scrapingRequested", "throughput research cannot trigger scraping"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX5DealThroughputDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x5DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX5DealThroughputOptimizationLayerDriftRiskAudit(input: X5DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X5DriftStatus = blockedReasons.length > 0 ? "x5_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x5_drift_audit_clear";
  return { phase: "X5C" as const, status, flags: x5DealThroughputFlags, riskCategories: x5DriftRiskCategories, blockedDriftTransitions: x5BlockedDriftTransitions, accessibility: x5AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
