import { x6AccessibilityRequirements, x6RevenueLeakageFlags } from "./x6-revenue-leakage-detection-scope-contract";

export type X6SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "outreachReviewed" | "routingReviewed" | "runtimeReviewed" | "contactReviewed" | "providerReviewed" | "escalationReviewed" | "skipTracingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "outreachRequested" | "routingRequested" | "runtimeRequested" | "contactRequested" | "providerRequested" | "escalationRequested" | "skipTracingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X6SafetyStatus = "x6_final_lockdown_blocked" | "operator_review_required" | "x6_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X6SafetyInput, string]> = [["executionReviewed", "revenue leakage detection does not execute"], ["automationReviewed", "revenue recommendations do not automate"], ["outreachReviewed", "stale opportunity review does not trigger outreach"], ["routingReviewed", "blocked revenue review does not route work"], ["runtimeReviewed", "delayed close review does not activate runtime jobs"], ["contactReviewed", "momentum-loss review does not trigger contact"], ["providerReviewed", "near-close-risk review does not activate providers"], ["escalationReviewed", "assignment-delay review does not escalate automatically"], ["skipTracingReviewed", "missing data review does not trigger skip tracing"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X6SafetyInput, string]> = [["executionRequested", "revenue leakage detection cannot execute"], ["automationRequested", "revenue recommendations cannot automate"], ["outreachRequested", "stale opportunity review cannot trigger outreach"], ["routingRequested", "blocked revenue review cannot route work"], ["runtimeRequested", "delayed close review cannot activate runtime jobs"], ["contactRequested", "momentum-loss review cannot trigger contact"], ["providerRequested", "near-close-risk review cannot activate providers"], ["escalationRequested", "assignment-delay review cannot escalate automatically"], ["skipTracingRequested", "missing data review cannot trigger skip tracing"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX6RevenueLeakageDetectionSafetyFinalLockdownReview(input: X6SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X6SafetyStatus = blockedReasons.length > 0 ? "x6_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x6_final_lockdown_clear";
  return { phase: "X6F" as const, status, flags: x6RevenueLeakageFlags, accessibility: x6AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
