import { x6AccessibilityRequirements, x6RevenueLeakageFlags } from "./x6-revenue-leakage-detection-scope-contract";

export const x6DriftRiskCategories = ["revenue-review-to-execution drift", "stale-opportunity-to-outreach drift", "blocked-revenue-to-routing drift", "delayed-close-to-runtime drift", "workflow-friction-to-automation drift", "momentum-loss-to-contact drift", "near-close-risk-to-provider drift", "assignment-delay-to-escalation drift", "missing-data-to-skip-tracing drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x6DangerousWordingPatterns = ["send", "blast", "recover automatically", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "escalate automatically", "skip trace", "scrape records"] as const;
export const x6BlockedDriftTransitions = ["revenue review cannot execute", "stale opportunity cannot trigger outreach", "blocked revenue cannot route work", "delayed close cannot activate runtime jobs", "workflow friction cannot activate automation", "momentum loss cannot trigger contact", "near-close risk cannot activate providers", "assignment delay cannot escalate automatically", "missing data cannot trigger skip tracing", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X6DriftInput = Partial<Record<"executionReviewed" | "outreachReviewed" | "routingReviewed" | "runtimeReviewed" | "automationReviewed" | "contactReviewed" | "providerReviewed" | "escalationReviewed" | "skipTracingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "outreachRequested" | "routingRequested" | "runtimeRequested" | "automationRequested" | "contactRequested" | "providerRequested" | "escalationRequested" | "skipTracingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X6DriftStatus = "x6_drift_blocked" | "operator_review_required" | "x6_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X6DriftInput, string]> = [["executionReviewed", "revenue-review-to-execution drift"], ["outreachReviewed", "stale-opportunity-to-outreach drift"], ["routingReviewed", "blocked-revenue-to-routing drift"], ["runtimeReviewed", "delayed-close-to-runtime drift"], ["automationReviewed", "workflow-friction-to-automation drift"], ["contactReviewed", "momentum-loss-to-contact drift"], ["providerReviewed", "near-close-risk-to-provider drift"], ["escalationReviewed", "assignment-delay-to-escalation drift"], ["skipTracingReviewed", "missing-data-to-skip-tracing drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X6DriftInput, string]> = [["executionRequested", "revenue review cannot execute"], ["outreachRequested", "stale opportunity cannot trigger outreach"], ["routingRequested", "blocked revenue cannot route work"], ["runtimeRequested", "delayed close cannot activate runtime jobs"], ["automationRequested", "workflow friction cannot activate automation"], ["contactRequested", "momentum loss cannot trigger contact"], ["providerRequested", "near-close risk cannot activate providers"], ["escalationRequested", "assignment delay cannot escalate automatically"], ["skipTracingRequested", "missing data cannot trigger skip tracing"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX6RevenueLeakageDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x6DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX6RevenueLeakageDetectionDriftRiskAudit(input: X6DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X6DriftStatus = blockedReasons.length > 0 ? "x6_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x6_drift_audit_clear";
  return { phase: "X6C" as const, status, flags: x6RevenueLeakageFlags, riskCategories: x6DriftRiskCategories, blockedDriftTransitions: x6BlockedDriftTransitions, accessibility: x6AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
