import { x7AccessibilityRequirements, x7NearCloseDealRecoveryFlags } from "./x7-near-close-deal-recovery-operations-scope-contract";

export const x7DriftRiskCategories = ["near-close-recovery-to-execution drift", "recovery-recommendation-to-automation drift", "stalled-near-close-to-outreach drift", "blocked-closing-to-routing drift", "closing-risk-to-runtime drift", "assignment-risk-to-provider drift", "buyer-readiness-to-contact drift", "seller-readiness-to-contact drift", "missing-closing-data-to-skip-tracing drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x7DangerousWordingPatterns = ["send", "blast", "recover automatically", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "escalate automatically", "skip trace", "scrape records"] as const;
export const x7BlockedDriftTransitions = ["near-close recovery cannot execute", "recovery recommendations cannot automate", "stalled near-close items cannot trigger outreach", "blocked closing cannot route work", "closing risk cannot activate runtime jobs", "assignment risk cannot activate providers", "buyer readiness cannot trigger contact", "seller readiness cannot trigger contact", "missing closing data cannot trigger skip tracing", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X7DriftInput = Partial<Record<"executionReviewed" | "automationReviewed" | "outreachReviewed" | "routingReviewed" | "runtimeReviewed" | "providerReviewed" | "buyerContactReviewed" | "sellerContactReviewed" | "skipTracingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "outreachRequested" | "routingRequested" | "runtimeRequested" | "providerRequested" | "buyerContactRequested" | "sellerContactRequested" | "skipTracingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X7DriftStatus = "x7_drift_blocked" | "operator_review_required" | "x7_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X7DriftInput, string]> = [["executionReviewed", "near-close-recovery-to-execution drift"], ["automationReviewed", "recovery-recommendation-to-automation drift"], ["outreachReviewed", "stalled-near-close-to-outreach drift"], ["routingReviewed", "blocked-closing-to-routing drift"], ["runtimeReviewed", "closing-risk-to-runtime drift"], ["providerReviewed", "assignment-risk-to-provider drift"], ["buyerContactReviewed", "buyer-readiness-to-contact drift"], ["sellerContactReviewed", "seller-readiness-to-contact drift"], ["skipTracingReviewed", "missing-closing-data-to-skip-tracing drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X7DriftInput, string]> = [["executionRequested", "near-close recovery cannot execute"], ["automationRequested", "recovery recommendations cannot automate"], ["outreachRequested", "stalled near-close items cannot trigger outreach"], ["routingRequested", "blocked closing cannot route work"], ["runtimeRequested", "closing risk cannot activate runtime jobs"], ["providerRequested", "assignment risk cannot activate providers"], ["buyerContactRequested", "buyer readiness cannot trigger contact"], ["sellerContactRequested", "seller readiness cannot trigger contact"], ["skipTracingRequested", "missing closing data cannot trigger skip tracing"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX7NearCloseDealRecoveryDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x7DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX7NearCloseDealRecoveryOperationsDriftRiskAudit(input: X7DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X7DriftStatus = blockedReasons.length > 0 ? "x7_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x7_drift_audit_clear";
  return { phase: "X7C" as const, status, flags: x7NearCloseDealRecoveryFlags, riskCategories: x7DriftRiskCategories, blockedDriftTransitions: x7BlockedDriftTransitions, accessibility: x7AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
