import { x7AccessibilityRequirements, x7NearCloseDealRecoveryFlags } from "./x7-near-close-deal-recovery-operations-scope-contract";

export type X7SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "outreachReviewed" | "routingReviewed" | "runtimeReviewed" | "providerReviewed" | "buyerContactReviewed" | "sellerContactReviewed" | "skipTracingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "outreachRequested" | "routingRequested" | "runtimeRequested" | "providerRequested" | "buyerContactRequested" | "sellerContactRequested" | "skipTracingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X7SafetyStatus = "x7_final_lockdown_blocked" | "operator_review_required" | "x7_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X7SafetyInput, string]> = [["executionReviewed", "near-close deal recovery does not execute"], ["automationReviewed", "recovery recommendations do not automate"], ["outreachReviewed", "stalled near-close review does not trigger outreach"], ["routingReviewed", "blocked closing review does not route work"], ["runtimeReviewed", "closing-risk review does not activate runtime jobs"], ["providerReviewed", "assignment-risk review does not activate providers"], ["buyerContactReviewed", "buyer readiness review does not trigger contact"], ["sellerContactReviewed", "seller readiness review does not trigger contact"], ["skipTracingReviewed", "missing closing data review does not trigger skip tracing"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X7SafetyInput, string]> = [["executionRequested", "near-close deal recovery cannot execute"], ["automationRequested", "recovery recommendations cannot automate"], ["outreachRequested", "stalled near-close review cannot trigger outreach"], ["routingRequested", "blocked closing review cannot route work"], ["runtimeRequested", "closing-risk review cannot activate runtime jobs"], ["providerRequested", "assignment-risk review cannot activate providers"], ["buyerContactRequested", "buyer readiness review cannot trigger contact"], ["sellerContactRequested", "seller readiness review cannot trigger contact"], ["skipTracingRequested", "missing closing data review cannot trigger skip tracing"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX7NearCloseDealRecoveryOperationsSafetyFinalLockdownReview(input: X7SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X7SafetyStatus = blockedReasons.length > 0 ? "x7_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x7_final_lockdown_clear";
  return { phase: "X7F" as const, status, flags: x7NearCloseDealRecoveryFlags, accessibility: x7AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
