import { x8AccessibilityRequirements, x8HumanApprovedCommunicationFlags } from "./x8-human-approved-communication-workspace-scope-contract";

export const x8DriftRiskCategories = ["communication-review-to-execution drift", "communication-readiness-to-send drift", "approval-review-to-provider drift", "communication-context-to-outreach drift", "communication-risk-to-routing drift", "provider-blocked-to-provider-activation drift", "DNC-review-to-contact drift", "opt-out-review-to-outreach drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x8DangerousWordingPatterns = ["send now", "blast", "auto-send", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "override dnc", "bypass opt-out", "scrape records"] as const;
export const x8BlockedDriftTransitions = ["communication review cannot execute", "communication readiness cannot send", "approval review cannot activate providers", "communication context cannot trigger outreach", "communication risk cannot route work", "provider-blocked review cannot activate providers", "DNC review cannot permit contact", "opt-out review cannot trigger outreach", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X8DriftInput = Partial<Record<"executionReviewed" | "sendReviewed" | "providerReviewed" | "outreachReviewed" | "routingReviewed" | "providerBlockedReviewed" | "dncContactReviewed" | "optOutOutreachReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "sendRequested" | "providerRequested" | "outreachRequested" | "routingRequested" | "providerBlockedActivationRequested" | "dncContactRequested" | "optOutOutreachRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X8DriftStatus = "x8_drift_blocked" | "operator_review_required" | "x8_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X8DriftInput, string]> = [["executionReviewed", "communication-review-to-execution drift"], ["sendReviewed", "communication-readiness-to-send drift"], ["providerReviewed", "approval-review-to-provider drift"], ["outreachReviewed", "communication-context-to-outreach drift"], ["routingReviewed", "communication-risk-to-routing drift"], ["providerBlockedReviewed", "provider-blocked-to-provider-activation drift"], ["dncContactReviewed", "DNC-review-to-contact drift"], ["optOutOutreachReviewed", "opt-out-review-to-outreach drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X8DriftInput, string]> = [["executionRequested", "communication review cannot execute"], ["sendRequested", "communication readiness cannot send"], ["providerRequested", "approval review cannot activate providers"], ["outreachRequested", "communication context cannot trigger outreach"], ["routingRequested", "communication risk cannot route work"], ["providerBlockedActivationRequested", "provider-blocked review cannot activate providers"], ["dncContactRequested", "DNC review cannot permit contact"], ["optOutOutreachRequested", "opt-out review cannot trigger outreach"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX8CommunicationWorkspaceDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x8DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX8HumanApprovedCommunicationWorkspaceDriftRiskAudit(input: X8DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X8DriftStatus = blockedReasons.length > 0 ? "x8_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x8_drift_audit_clear";
  return { phase: "X8C" as const, status, flags: x8HumanApprovedCommunicationFlags, riskCategories: x8DriftRiskCategories, blockedDriftTransitions: x8BlockedDriftTransitions, accessibility: x8AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
