import { x8AccessibilityRequirements, x8HumanApprovedCommunicationFlags } from "./x8-human-approved-communication-workspace-scope-contract";

export type X8SafetyInput = Partial<Record<"executionReviewed" | "automationReviewed" | "sendReviewed" | "providerReviewed" | "outreachReviewed" | "dncOptOutReviewed" | "providerBlockedReviewed" | "routingReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "automationRequested" | "sendRequested" | "providerRequested" | "outreachRequested" | "dncOptOutContactRequested" | "providerBlockedActivationRequested" | "routingRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X8SafetyStatus = "x8_final_lockdown_blocked" | "operator_review_required" | "x8_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X8SafetyInput, string]> = [["executionReviewed", "communication workspace does not execute"], ["automationReviewed", "communication recommendations do not automate"], ["sendReviewed", "communication readiness review does not send"], ["providerReviewed", "human approval review does not activate providers"], ["outreachReviewed", "communication risk review does not trigger outreach"], ["dncOptOutReviewed", "DNC/opt-out review does not permit contact"], ["providerBlockedReviewed", "provider-blocked review does not activate providers"], ["routingReviewed", "communication context review does not route work"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X8SafetyInput, string]> = [["executionRequested", "communication workspace cannot execute"], ["automationRequested", "communication recommendations cannot automate"], ["sendRequested", "communication readiness cannot send"], ["providerRequested", "human approval review cannot activate providers"], ["outreachRequested", "communication risk review cannot trigger outreach"], ["dncOptOutContactRequested", "DNC/opt-out review cannot permit contact"], ["providerBlockedActivationRequested", "provider-blocked review cannot activate providers"], ["routingRequested", "communication context review cannot route work"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX8HumanApprovedCommunicationWorkspaceSafetyFinalLockdownReview(input: X8SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X8SafetyStatus = blockedReasons.length > 0 ? "x8_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x8_final_lockdown_clear";
  return { phase: "X8F" as const, status, flags: x8HumanApprovedCommunicationFlags, accessibility: x8AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
