import { x9AccessibilityRequirements, x9ControlledExecutionReadinessFlags } from "./x9-controlled-execution-readiness-scope-contract";

export const x9DriftRiskCategories = ["readiness-to-execution drift", "readiness-to-activation drift", "readiness-to-approval-execution drift", "provider-readiness-to-provider-activation drift", "runtime-readiness-to-runtime-job drift", "outreach-readiness-to-outreach drift", "routing-readiness-to-routing drift", "readiness-to-automation drift", "external API drift", "fetch/network drift", "persistence drift", "audit-writing drift", "dangerous wording drift"] as const;
export const x9DangerousWordingPatterns = ["ready to execute", "ready to activate", "approved for execution", "execute", "activate", "launch", "route work", "start automation", "trigger outreach", "contact seller", "contact buyer", "send now", "enable provider", "run workflow"] as const;
export const x9BlockedDriftTransitions = ["readiness cannot execute", "readiness cannot activate anything", "readiness cannot grant approval execution", "provider readiness cannot activate providers", "runtime readiness cannot activate runtime jobs", "outreach readiness cannot trigger outreach", "routing readiness cannot route work", "readiness cannot activate automation", "fetch/network remains blocked", "persistence remains blocked", "audit writing remains blocked"] as const;

export type X9DriftInput = Partial<Record<"executionReviewed" | "activationReviewed" | "approvalExecutionReviewed" | "providerReviewed" | "runtimeReviewed" | "outreachReviewed" | "routingReviewed" | "automationReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "dangerousWordingReviewed" | "accessibilityReviewed", boolean>> & Partial<Record<"executionRequested" | "activationRequested" | "approvalExecutionRequested" | "providerRequested" | "runtimeRequested" | "outreachRequested" | "routingRequested" | "automationRequested" | "externalApiRequested" | "fetchNetworkRequested" | "persistenceRequested" | "auditWritingRequested" | "dangerousWordingRequested", boolean>>;
export type X9DriftStatus = "x9_drift_blocked" | "operator_review_required" | "x9_drift_audit_clear";

const requiredReviewAreas: Array<[keyof X9DriftInput, string]> = [["executionReviewed", "readiness-to-execution drift"], ["activationReviewed", "readiness-to-activation drift"], ["approvalExecutionReviewed", "readiness-to-approval-execution drift"], ["providerReviewed", "provider-readiness-to-provider-activation drift"], ["runtimeReviewed", "runtime-readiness-to-runtime-job drift"], ["outreachReviewed", "outreach-readiness-to-outreach drift"], ["routingReviewed", "routing-readiness-to-routing drift"], ["automationReviewed", "readiness-to-automation drift"], ["externalApiReviewed", "external API drift"], ["fetchNetworkReviewed", "fetch/network drift"], ["persistenceReviewed", "persistence drift"], ["auditWritingReviewed", "audit-writing drift"], ["dangerousWordingReviewed", "dangerous wording drift"], ["accessibilityReviewed", "accessibility drift"]];
const blockedRequests: Array<[keyof X9DriftInput, string]> = [["executionRequested", "readiness cannot execute"], ["activationRequested", "readiness cannot activate anything"], ["approvalExecutionRequested", "readiness cannot grant approval execution"], ["providerRequested", "provider readiness cannot activate providers"], ["runtimeRequested", "runtime readiness cannot activate runtime jobs"], ["outreachRequested", "outreach readiness cannot trigger outreach"], ["routingRequested", "routing readiness cannot route work"], ["automationRequested", "readiness cannot activate automation"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["dangerousWordingRequested", "dangerous wording remains blocked"]];

export function classifyX9ControlledExecutionReadinessDangerousWording(text: string): "dangerous_wording_detected" | "wording_clear" {
  const normalized = text.toLowerCase();
  return x9DangerousWordingPatterns.some((pattern) => normalized.includes(pattern)) ? "dangerous_wording_detected" : "wording_clear";
}

export function createX9ControlledExecutionReadinessDriftRiskAudit(input: X9DriftInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X9DriftStatus = blockedReasons.length > 0 ? "x9_drift_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x9_drift_audit_clear";
  return { phase: "X9C" as const, status, flags: x9ControlledExecutionReadinessFlags, riskCategories: x9DriftRiskCategories, blockedDriftTransitions: x9BlockedDriftTransitions, accessibility: x9AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
