import { x9AccessibilityRequirements, x9ControlledExecutionReadinessFlags } from "./x9-controlled-execution-readiness-scope-contract";

export type X9SafetyInput = Partial<Record<"executionReviewed" | "activationReviewed" | "approvalExecutionReviewed" | "providerReviewed" | "runtimeReviewed" | "outreachReviewed" | "routingReviewed" | "automationReviewed" | "persistenceReviewed" | "auditWritingReviewed" | "pollingReviewed" | "externalApiReviewed" | "fetchNetworkReviewed" | "processEnvReviewed" | "accessibilityReviewed" | "governanceWarningsReviewed", boolean>> & Partial<Record<"executionRequested" | "activationRequested" | "approvalExecutionRequested" | "providerRequested" | "runtimeRequested" | "outreachRequested" | "routingRequested" | "automationRequested" | "persistenceRequested" | "auditWritingRequested" | "pollingRequested" | "externalApiRequested" | "fetchNetworkRequested" | "processEnvRequested", boolean>>;
export type X9SafetyStatus = "x9_final_lockdown_blocked" | "operator_review_required" | "x9_final_lockdown_clear";

const requiredReviewAreas: Array<[keyof X9SafetyInput, string]> = [["executionReviewed", "controlled execution readiness does not execute"], ["activationReviewed", "readiness does not authorize activation"], ["approvalExecutionReviewed", "readiness does not grant approval execution"], ["providerReviewed", "provider readiness does not activate providers"], ["runtimeReviewed", "runtime readiness does not activate runtime jobs"], ["outreachReviewed", "outreach readiness does not trigger outreach"], ["routingReviewed", "routing readiness does not route work"], ["automationReviewed", "readiness recommendations do not automate"], ["persistenceReviewed", "no persistence"], ["auditWritingReviewed", "no audit writing"], ["pollingReviewed", "no polling/runtime"], ["externalApiReviewed", "no external API"], ["fetchNetworkReviewed", "no fetch/network"], ["processEnvReviewed", "no process.env"], ["accessibilityReviewed", "accessibility preserved"], ["governanceWarningsReviewed", "visible governance warnings"]];
const blockedRequests: Array<[keyof X9SafetyInput, string]> = [["executionRequested", "controlled execution readiness cannot execute"], ["activationRequested", "readiness cannot authorize activation"], ["approvalExecutionRequested", "readiness cannot grant approval execution"], ["providerRequested", "provider readiness cannot activate providers"], ["runtimeRequested", "runtime readiness cannot activate runtime jobs"], ["outreachRequested", "outreach readiness cannot trigger outreach"], ["routingRequested", "routing readiness cannot route work"], ["automationRequested", "readiness recommendations cannot automate"], ["persistenceRequested", "persistence remains blocked"], ["auditWritingRequested", "audit writing remains blocked"], ["pollingRequested", "polling remains blocked"], ["externalApiRequested", "external API remains blocked"], ["fetchNetworkRequested", "fetch/network remains blocked"], ["processEnvRequested", "process.env remains blocked"]];

export function createX9ControlledExecutionReadinessSafetyFinalLockdownReview(input: X9SafetyInput = {}) {
  const missingReviewAreas = requiredReviewAreas.filter(([key]) => !input[key]).map(([, label]) => label);
  const blockedReasons = blockedRequests.filter(([key]) => input[key]).map(([, label]) => label);
  const status: X9SafetyStatus = blockedReasons.length > 0 ? "x9_final_lockdown_blocked" : missingReviewAreas.length > 0 ? "operator_review_required" : "x9_final_lockdown_clear";
  return { phase: "X9F" as const, status, flags: x9ControlledExecutionReadinessFlags, accessibility: x9AccessibilityRequirements, missingReviewAreas, blockedReasons };
}
